// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/entrypoint/process/mysql.proto

package process

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mysql struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DependencyId  string                 `protobuf:"bytes,1,opt,name=dependency_id,json=dependencyId,proto3" json:"dependency_id,omitempty"`
	Queries       []*Query               `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mysql) Reset() {
	*x = Mysql{}
	mi := &file_core_entrypoint_process_mysql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mysql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mysql) ProtoMessage() {}

func (x *Mysql) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_process_mysql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mysql.ProtoReflect.Descriptor instead.
func (*Mysql) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_process_mysql_proto_rawDescGZIP(), []int{0}
}

func (x *Mysql) GetDependencyId() string {
	if x != nil {
		return x.DependencyId
	}
	return ""
}

func (x *Mysql) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

var File_core_entrypoint_process_mysql_proto protoreflect.FileDescriptor

const file_core_entrypoint_process_mysql_proto_rawDesc = "" +
	"\n" +
	"#core/entrypoint/process/mysql.proto\x12\aprocess\x1a#core/entrypoint/process/query.proto\"V\n" +
	"\x05Mysql\x12#\n" +
	"\rdependency_id\x18\x01 \x01(\tR\fdependencyId\x12(\n" +
	"\aqueries\x18\x02 \x03(\v2\x0e.process.QueryR\aqueriesB\x8f\x01\n" +
	"\vcom.processB\n" +
	"MysqlProtoP\x01Z8github.com/ideagate/model/gen-go/core/entrypoint/process\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_core_entrypoint_process_mysql_proto_rawDescOnce sync.Once
	file_core_entrypoint_process_mysql_proto_rawDescData []byte
)

func file_core_entrypoint_process_mysql_proto_rawDescGZIP() []byte {
	file_core_entrypoint_process_mysql_proto_rawDescOnce.Do(func() {
		file_core_entrypoint_process_mysql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_entrypoint_process_mysql_proto_rawDesc), len(file_core_entrypoint_process_mysql_proto_rawDesc)))
	})
	return file_core_entrypoint_process_mysql_proto_rawDescData
}

var file_core_entrypoint_process_mysql_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_entrypoint_process_mysql_proto_goTypes = []any{
	(*Mysql)(nil), // 0: process.Mysql
	(*Query)(nil), // 1: process.Query
}
var file_core_entrypoint_process_mysql_proto_depIdxs = []int32{
	1, // 0: process.Mysql.queries:type_name -> process.Query
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_entrypoint_process_mysql_proto_init() }
func file_core_entrypoint_process_mysql_proto_init() {
	if File_core_entrypoint_process_mysql_proto != nil {
		return
	}
	file_core_entrypoint_process_query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_entrypoint_process_mysql_proto_rawDesc), len(file_core_entrypoint_process_mysql_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_entrypoint_process_mysql_proto_goTypes,
		DependencyIndexes: file_core_entrypoint_process_mysql_proto_depIdxs,
		MessageInfos:      file_core_entrypoint_process_mysql_proto_msgTypes,
	}.Build()
	File_core_entrypoint_process_mysql_proto = out.File
	file_core_entrypoint_process_mysql_proto_goTypes = nil
	file_core_entrypoint_process_mysql_proto_depIdxs = nil
}
