// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/entrypoint/process/nats.proto

package process

import (
	variable "github.com/ideagate/model/gen-go/core/entrypoint/variable"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NatsPublisher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DependencyId  string                 `protobuf:"bytes,1,opt,name=dependency_id,json=dependencyId,proto3" json:"dependency_id,omitempty"`
	Subject       *variable.Variable     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       *variable.Variable     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatsPublisher) Reset() {
	*x = NatsPublisher{}
	mi := &file_core_entrypoint_process_nats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatsPublisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsPublisher) ProtoMessage() {}

func (x *NatsPublisher) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_process_nats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsPublisher.ProtoReflect.Descriptor instead.
func (*NatsPublisher) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_process_nats_proto_rawDescGZIP(), []int{0}
}

func (x *NatsPublisher) GetDependencyId() string {
	if x != nil {
		return x.DependencyId
	}
	return ""
}

func (x *NatsPublisher) GetSubject() *variable.Variable {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *NatsPublisher) GetMessage() *variable.Variable {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_core_entrypoint_process_nats_proto protoreflect.FileDescriptor

const file_core_entrypoint_process_nats_proto_rawDesc = "" +
	"\n" +
	"\"core/entrypoint/process/nats.proto\x12\aprocess\x1a'core/entrypoint/variable/variable.proto\"\x90\x01\n" +
	"\rNatsPublisher\x12#\n" +
	"\rdependency_id\x18\x01 \x01(\tR\fdependencyId\x12,\n" +
	"\asubject\x18\x02 \x01(\v2\x12.variable.VariableR\asubject\x12,\n" +
	"\amessage\x18\x03 \x01(\v2\x12.variable.VariableR\amessageB\x8e\x01\n" +
	"\vcom.processB\tNatsProtoP\x01Z8github.com/ideagate/model/gen-go/core/entrypoint/process\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_core_entrypoint_process_nats_proto_rawDescOnce sync.Once
	file_core_entrypoint_process_nats_proto_rawDescData []byte
)

func file_core_entrypoint_process_nats_proto_rawDescGZIP() []byte {
	file_core_entrypoint_process_nats_proto_rawDescOnce.Do(func() {
		file_core_entrypoint_process_nats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_entrypoint_process_nats_proto_rawDesc), len(file_core_entrypoint_process_nats_proto_rawDesc)))
	})
	return file_core_entrypoint_process_nats_proto_rawDescData
}

var file_core_entrypoint_process_nats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_entrypoint_process_nats_proto_goTypes = []any{
	(*NatsPublisher)(nil),     // 0: process.NatsPublisher
	(*variable.Variable)(nil), // 1: variable.Variable
}
var file_core_entrypoint_process_nats_proto_depIdxs = []int32{
	1, // 0: process.NatsPublisher.subject:type_name -> variable.Variable
	1, // 1: process.NatsPublisher.message:type_name -> variable.Variable
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_entrypoint_process_nats_proto_init() }
func file_core_entrypoint_process_nats_proto_init() {
	if File_core_entrypoint_process_nats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_entrypoint_process_nats_proto_rawDesc), len(file_core_entrypoint_process_nats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_entrypoint_process_nats_proto_goTypes,
		DependencyIndexes: file_core_entrypoint_process_nats_proto_depIdxs,
		MessageInfos:      file_core_entrypoint_process_nats_proto_msgTypes,
	}.Build()
	File_core_entrypoint_process_nats_proto = out.File
	file_core_entrypoint_process_nats_proto_goTypes = nil
	file_core_entrypoint_process_nats_proto_depIdxs = nil
}
