// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/entrypoint/process/process.proto

package process

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Process struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start start = 1;
	// End end = 2;
	Switch        *Switch        `protobuf:"bytes,3,opt,name=switch,proto3" json:"switch,omitempty"`
	Variables     *Variables     `protobuf:"bytes,4,opt,name=variables,proto3" json:"variables,omitempty"`
	Mysql         *Mysql         `protobuf:"bytes,5,opt,name=mysql,proto3" json:"mysql,omitempty"`
	NatsPublisher *NatsPublisher `protobuf:"bytes,6,opt,name=nats_publisher,json=natsPublisher,proto3" json:"nats_publisher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_core_entrypoint_process_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_process_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_process_process_proto_rawDescGZIP(), []int{0}
}

func (x *Process) GetSwitch() *Switch {
	if x != nil {
		return x.Switch
	}
	return nil
}

func (x *Process) GetVariables() *Variables {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Process) GetMysql() *Mysql {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Process) GetNatsPublisher() *NatsPublisher {
	if x != nil {
		return x.NatsPublisher
	}
	return nil
}

var File_core_entrypoint_process_process_proto protoreflect.FileDescriptor

const file_core_entrypoint_process_process_proto_rawDesc = "" +
	"\n" +
	"%core/entrypoint/process/process.proto\x12\aprocess\x1a$core/entrypoint/process/switch.proto\x1a&core/entrypoint/process/variable.proto\x1a#core/entrypoint/process/mysql.proto\x1a\"core/entrypoint/process/nats.proto\"\xc9\x01\n" +
	"\aProcess\x12'\n" +
	"\x06switch\x18\x03 \x01(\v2\x0f.process.SwitchR\x06switch\x120\n" +
	"\tvariables\x18\x04 \x01(\v2\x12.process.VariablesR\tvariables\x12$\n" +
	"\x05mysql\x18\x05 \x01(\v2\x0e.process.MysqlR\x05mysql\x12=\n" +
	"\x0enats_publisher\x18\x06 \x01(\v2\x16.process.NatsPublisherR\rnatsPublisherB\x91\x01\n" +
	"\vcom.processB\fProcessProtoP\x01Z8github.com/ideagate/model/gen-go/core/entrypoint/process\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_core_entrypoint_process_process_proto_rawDescOnce sync.Once
	file_core_entrypoint_process_process_proto_rawDescData []byte
)

func file_core_entrypoint_process_process_proto_rawDescGZIP() []byte {
	file_core_entrypoint_process_process_proto_rawDescOnce.Do(func() {
		file_core_entrypoint_process_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_entrypoint_process_process_proto_rawDesc), len(file_core_entrypoint_process_process_proto_rawDesc)))
	})
	return file_core_entrypoint_process_process_proto_rawDescData
}

var file_core_entrypoint_process_process_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_entrypoint_process_process_proto_goTypes = []any{
	(*Process)(nil),       // 0: process.Process
	(*Switch)(nil),        // 1: process.Switch
	(*Variables)(nil),     // 2: process.Variables
	(*Mysql)(nil),         // 3: process.Mysql
	(*NatsPublisher)(nil), // 4: process.NatsPublisher
}
var file_core_entrypoint_process_process_proto_depIdxs = []int32{
	1, // 0: process.Process.switch:type_name -> process.Switch
	2, // 1: process.Process.variables:type_name -> process.Variables
	3, // 2: process.Process.mysql:type_name -> process.Mysql
	4, // 3: process.Process.nats_publisher:type_name -> process.NatsPublisher
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_entrypoint_process_process_proto_init() }
func file_core_entrypoint_process_process_proto_init() {
	if File_core_entrypoint_process_process_proto != nil {
		return
	}
	file_core_entrypoint_process_switch_proto_init()
	file_core_entrypoint_process_variable_proto_init()
	file_core_entrypoint_process_mysql_proto_init()
	file_core_entrypoint_process_nats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_entrypoint_process_process_proto_rawDesc), len(file_core_entrypoint_process_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_entrypoint_process_process_proto_goTypes,
		DependencyIndexes: file_core_entrypoint_process_process_proto_depIdxs,
		MessageInfos:      file_core_entrypoint_process_process_proto_msgTypes,
	}.Build()
	File_core_entrypoint_process_process_proto = out.File
	file_core_entrypoint_process_process_proto_goTypes = nil
	file_core_entrypoint_process_process_proto_depIdxs = nil
}
