// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/entrypoint/process/variable.proto

package process

import (
	variable "github.com/ideagate/model/gen-go/core/entrypoint/variable"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Variables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*VariablesAction     `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variables) Reset() {
	*x = Variables{}
	mi := &file_core_entrypoint_process_variable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variables) ProtoMessage() {}

func (x *Variables) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_process_variable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variables.ProtoReflect.Descriptor instead.
func (*Variables) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_process_variable_proto_rawDescGZIP(), []int{0}
}

func (x *Variables) GetActions() []*VariablesAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type VariablesAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	VariableName  string                 `protobuf:"bytes,2,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	Value         *variable.Variable     `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariablesAction) Reset() {
	*x = VariablesAction{}
	mi := &file_core_entrypoint_process_variable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariablesAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariablesAction) ProtoMessage() {}

func (x *VariablesAction) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_process_variable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariablesAction.ProtoReflect.Descriptor instead.
func (*VariablesAction) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_process_variable_proto_rawDescGZIP(), []int{1}
}

func (x *VariablesAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VariablesAction) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *VariablesAction) GetValue() *variable.Variable {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_core_entrypoint_process_variable_proto protoreflect.FileDescriptor

const file_core_entrypoint_process_variable_proto_rawDesc = "" +
	"\n" +
	"&core/entrypoint/process/variable.proto\x12\aprocess\x1a'core/entrypoint/variable/variable.proto\"?\n" +
	"\tVariables\x122\n" +
	"\aactions\x18\x01 \x03(\v2\x18.process.VariablesActionR\aactions\"t\n" +
	"\x0fVariablesAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rvariable_name\x18\x02 \x01(\tR\fvariableName\x12(\n" +
	"\x05value\x18\x03 \x01(\v2\x12.variable.VariableR\x05valueB\x92\x01\n" +
	"\vcom.processB\rVariableProtoP\x01Z8github.com/ideagate/model/gen-go/core/entrypoint/process\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_core_entrypoint_process_variable_proto_rawDescOnce sync.Once
	file_core_entrypoint_process_variable_proto_rawDescData []byte
)

func file_core_entrypoint_process_variable_proto_rawDescGZIP() []byte {
	file_core_entrypoint_process_variable_proto_rawDescOnce.Do(func() {
		file_core_entrypoint_process_variable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_entrypoint_process_variable_proto_rawDesc), len(file_core_entrypoint_process_variable_proto_rawDesc)))
	})
	return file_core_entrypoint_process_variable_proto_rawDescData
}

var file_core_entrypoint_process_variable_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_entrypoint_process_variable_proto_goTypes = []any{
	(*Variables)(nil),         // 0: process.Variables
	(*VariablesAction)(nil),   // 1: process.VariablesAction
	(*variable.Variable)(nil), // 2: variable.Variable
}
var file_core_entrypoint_process_variable_proto_depIdxs = []int32{
	1, // 0: process.Variables.actions:type_name -> process.VariablesAction
	2, // 1: process.VariablesAction.value:type_name -> variable.Variable
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_entrypoint_process_variable_proto_init() }
func file_core_entrypoint_process_variable_proto_init() {
	if File_core_entrypoint_process_variable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_entrypoint_process_variable_proto_rawDesc), len(file_core_entrypoint_process_variable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_entrypoint_process_variable_proto_goTypes,
		DependencyIndexes: file_core_entrypoint_process_variable_proto_depIdxs,
		MessageInfos:      file_core_entrypoint_process_variable_proto_msgTypes,
	}.Build()
	File_core_entrypoint_process_variable_proto = out.File
	file_core_entrypoint_process_variable_proto_goTypes = nil
	file_core_entrypoint_process_variable_proto_depIdxs = nil
}
