// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/entrypoint/workflow/edge.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Edge struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	SourceOutputId string                 `protobuf:"bytes,3,opt,name=source_output_id,json=sourceOutputId,proto3" json:"source_output_id,omitempty"`
	Dest           string                 `protobuf:"bytes,4,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_core_entrypoint_workflow_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_workflow_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_workflow_edge_proto_rawDescGZIP(), []int{0}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetSourceOutputId() string {
	if x != nil {
		return x.SourceOutputId
	}
	return ""
}

func (x *Edge) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

var File_core_entrypoint_workflow_edge_proto protoreflect.FileDescriptor

const file_core_entrypoint_workflow_edge_proto_rawDesc = "" +
	"\n" +
	"#core/entrypoint/workflow/edge.proto\x12\bworkflow\"l\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12(\n" +
	"\x10source_output_id\x18\x03 \x01(\tR\x0esourceOutputId\x12\x12\n" +
	"\x04dest\x18\x04 \x01(\tR\x04destB\x94\x01\n" +
	"\fcom.workflowB\tEdgeProtoP\x01Z9github.com/ideagate/model/gen-go/core/entrypoint/workflow\xa2\x02\x03WXX\xaa\x02\bWorkflow\xca\x02\bWorkflow\xe2\x02\x14Workflow\\GPBMetadata\xea\x02\bWorkflowb\x06proto3"

var (
	file_core_entrypoint_workflow_edge_proto_rawDescOnce sync.Once
	file_core_entrypoint_workflow_edge_proto_rawDescData []byte
)

func file_core_entrypoint_workflow_edge_proto_rawDescGZIP() []byte {
	file_core_entrypoint_workflow_edge_proto_rawDescOnce.Do(func() {
		file_core_entrypoint_workflow_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_entrypoint_workflow_edge_proto_rawDesc), len(file_core_entrypoint_workflow_edge_proto_rawDesc)))
	})
	return file_core_entrypoint_workflow_edge_proto_rawDescData
}

var file_core_entrypoint_workflow_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_entrypoint_workflow_edge_proto_goTypes = []any{
	(*Edge)(nil), // 0: workflow.Edge
}
var file_core_entrypoint_workflow_edge_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_entrypoint_workflow_edge_proto_init() }
func file_core_entrypoint_workflow_edge_proto_init() {
	if File_core_entrypoint_workflow_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_entrypoint_workflow_edge_proto_rawDesc), len(file_core_entrypoint_workflow_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_entrypoint_workflow_edge_proto_goTypes,
		DependencyIndexes: file_core_entrypoint_workflow_edge_proto_depIdxs,
		MessageInfos:      file_core_entrypoint_workflow_edge_proto_msgTypes,
	}.Build()
	File_core_entrypoint_workflow_edge_proto = out.File
	file_core_entrypoint_workflow_edge_proto_goTypes = nil
	file_core_entrypoint_workflow_edge_proto_depIdxs = nil
}
