// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/entrypoint/workflow/workflow.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EntrypointId  string                 `protobuf:"bytes,2,opt,name=entrypoint_id,json=entrypointId,proto3" json:"entrypoint_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Steps         []*Step                `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,8,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_core_entrypoint_workflow_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_workflow_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_workflow_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *Workflow) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Workflow) GetEntrypointId() string {
	if x != nil {
		return x.EntrypointId
	}
	return ""
}

func (x *Workflow) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Workflow) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Workflow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workflow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Workflow) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Workflow) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_core_entrypoint_workflow_workflow_proto protoreflect.FileDescriptor

const file_core_entrypoint_workflow_workflow_proto_rawDesc = "" +
	"\n" +
	"'core/entrypoint/workflow/workflow.proto\x12\bworkflow\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#core/entrypoint/workflow/step.proto\x1a#core/entrypoint/workflow/edge.proto\"\xd1\x02\n" +
	"\bWorkflow\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12#\n" +
	"\rentrypoint_id\x18\x02 \x01(\tR\fentrypointId\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\x05steps\x18\a \x03(\v2\x0e.workflow.StepR\x05steps\x12$\n" +
	"\x05edges\x18\b \x03(\v2\x0e.workflow.EdgeR\x05edgesB\x98\x01\n" +
	"\fcom.workflowB\rWorkflowProtoP\x01Z9github.com/ideagate/model/gen-go/core/entrypoint/workflow\xa2\x02\x03WXX\xaa\x02\bWorkflow\xca\x02\bWorkflow\xe2\x02\x14Workflow\\GPBMetadata\xea\x02\bWorkflowb\x06proto3"

var (
	file_core_entrypoint_workflow_workflow_proto_rawDescOnce sync.Once
	file_core_entrypoint_workflow_workflow_proto_rawDescData []byte
)

func file_core_entrypoint_workflow_workflow_proto_rawDescGZIP() []byte {
	file_core_entrypoint_workflow_workflow_proto_rawDescOnce.Do(func() {
		file_core_entrypoint_workflow_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_entrypoint_workflow_workflow_proto_rawDesc), len(file_core_entrypoint_workflow_workflow_proto_rawDesc)))
	})
	return file_core_entrypoint_workflow_workflow_proto_rawDescData
}

var file_core_entrypoint_workflow_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_entrypoint_workflow_workflow_proto_goTypes = []any{
	(*Workflow)(nil),              // 0: workflow.Workflow
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Step)(nil),                  // 2: workflow.Step
	(*Edge)(nil),                  // 3: workflow.Edge
}
var file_core_entrypoint_workflow_workflow_proto_depIdxs = []int32{
	1, // 0: workflow.Workflow.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: workflow.Workflow.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: workflow.Workflow.steps:type_name -> workflow.Step
	3, // 3: workflow.Workflow.edges:type_name -> workflow.Edge
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_entrypoint_workflow_workflow_proto_init() }
func file_core_entrypoint_workflow_workflow_proto_init() {
	if File_core_entrypoint_workflow_workflow_proto != nil {
		return
	}
	file_core_entrypoint_workflow_step_proto_init()
	file_core_entrypoint_workflow_edge_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_entrypoint_workflow_workflow_proto_rawDesc), len(file_core_entrypoint_workflow_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_entrypoint_workflow_workflow_proto_goTypes,
		DependencyIndexes: file_core_entrypoint_workflow_workflow_proto_depIdxs,
		MessageInfos:      file_core_entrypoint_workflow_workflow_proto_msgTypes,
	}.Build()
	File_core_entrypoint_workflow_workflow_proto = out.File
	file_core_entrypoint_workflow_workflow_proto_goTypes = nil
	file_core_entrypoint_workflow_workflow_proto_depIdxs = nil
}
