// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/entrypoint/workflow/step.proto" (package "workflow", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Process } from "../process/process";
/**
 * @generated from protobuf message workflow.Step
 */
export interface Step {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: workflow.StepType type = 3;
     */
    type: StepType;
    /**
     * @generated from protobuf field: workflow.Graph graph = 7;
     */
    graph?: Graph;
    /**
     * @generated from protobuf field: process.Process process = 8;
     */
    process?: Process;
}
/**
 * @generated from protobuf message workflow.Graph
 */
export interface Graph {
    /**
     * @generated from protobuf field: int32 position_x = 1;
     */
    positionX: number;
    /**
     * @generated from protobuf field: int32 position_y = 2;
     */
    positionY: number;
}
/**
 * @generated from protobuf enum workflow.StepType
 */
export enum StepType {
    /**
     * @generated from protobuf enum value: STEP_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: STEP_TYPE_START = 1;
     */
    START = 1,
    /**
     * @generated from protobuf enum value: STEP_TYPE_END = 2;
     */
    END = 2,
    /**
     * @generated from protobuf enum value: STEP_TYPE_VARIABLES = 3;
     */
    VARIABLES = 3,
    /**
     * @generated from protobuf enum value: STEP_TYPE_SWITCH = 4;
     */
    SWITCH = 4,
    /**
     * @generated from protobuf enum value: STEP_TYPE_MYSQL = 5;
     */
    MYSQL = 5,
    /**
     * @generated from protobuf enum value: STEP_TYPE_NATS_PUBLISHER = 6;
     */
    NATS_PUBLISHER = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class Step$Type extends MessageType<Step> {
    constructor() {
        super("workflow.Step", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["workflow.StepType", StepType, "STEP_TYPE_"] },
            { no: 7, name: "graph", kind: "message", T: () => Graph },
            { no: 8, name: "process", kind: "message", T: () => Process }
        ]);
    }
    create(value?: PartialMessage<Step>): Step {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.type = 0;
        if (value !== undefined)
            reflectionMergePartial<Step>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Step): Step {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* workflow.StepType type */ 3:
                    message.type = reader.int32();
                    break;
                case /* workflow.Graph graph */ 7:
                    message.graph = Graph.internalBinaryRead(reader, reader.uint32(), options, message.graph);
                    break;
                case /* process.Process process */ 8:
                    message.process = Process.internalBinaryRead(reader, reader.uint32(), options, message.process);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Step, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* workflow.StepType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* workflow.Graph graph = 7; */
        if (message.graph)
            Graph.internalBinaryWrite(message.graph, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* process.Process process = 8; */
        if (message.process)
            Process.internalBinaryWrite(message.process, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workflow.Step
 */
export const Step = new Step$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Graph$Type extends MessageType<Graph> {
    constructor() {
        super("workflow.Graph", [
            { no: 1, name: "position_x", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "position_y", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Graph>): Graph {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionX = 0;
        message.positionY = 0;
        if (value !== undefined)
            reflectionMergePartial<Graph>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Graph): Graph {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 position_x */ 1:
                    message.positionX = reader.int32();
                    break;
                case /* int32 position_y */ 2:
                    message.positionY = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Graph, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 position_x = 1; */
        if (message.positionX !== 0)
            writer.tag(1, WireType.Varint).int32(message.positionX);
        /* int32 position_y = 2; */
        if (message.positionY !== 0)
            writer.tag(2, WireType.Varint).int32(message.positionY);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workflow.Graph
 */
export const Graph = new Graph$Type();
