// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/entrypoint/workflow/workflow.proto" (package "workflow", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Edge } from "./edge";
import { Step } from "./step";
import { Timestamp } from "../../../google/protobuf/timestamp";
/**
 * @generated from protobuf message workflow.Workflow
 */
export interface Workflow {
    /**
     * @generated from protobuf field: int64 version = 1;
     */
    version: bigint;
    /**
     * @generated from protobuf field: string entrypoint_id = 2;
     */
    entrypointId: string;
    /**
     * @generated from protobuf field: string application_id = 3;
     */
    applicationId: string;
    /**
     * @generated from protobuf field: string project_id = 4;
     */
    projectId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 5;
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 6;
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: repeated workflow.Step steps = 7;
     */
    steps: Step[];
    /**
     * @generated from protobuf field: repeated workflow.Edge edges = 8;
     */
    edges: Edge[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Workflow$Type extends MessageType<Workflow> {
    constructor() {
        super("workflow.Workflow", [
            { no: 1, name: "version", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "entrypoint_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "application_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "project_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 6, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 7, name: "steps", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Step },
            { no: 8, name: "edges", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Edge }
        ]);
    }
    create(value?: PartialMessage<Workflow>): Workflow {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.version = 0n;
        message.entrypointId = "";
        message.applicationId = "";
        message.projectId = "";
        message.steps = [];
        message.edges = [];
        if (value !== undefined)
            reflectionMergePartial<Workflow>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Workflow): Workflow {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 version */ 1:
                    message.version = reader.int64().toBigInt();
                    break;
                case /* string entrypoint_id */ 2:
                    message.entrypointId = reader.string();
                    break;
                case /* string application_id */ 3:
                    message.applicationId = reader.string();
                    break;
                case /* string project_id */ 4:
                    message.projectId = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 5:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 6:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* repeated workflow.Step steps */ 7:
                    message.steps.push(Step.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated workflow.Edge edges */ 8:
                    message.edges.push(Edge.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Workflow, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 version = 1; */
        if (message.version !== 0n)
            writer.tag(1, WireType.Varint).int64(message.version);
        /* string entrypoint_id = 2; */
        if (message.entrypointId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.entrypointId);
        /* string application_id = 3; */
        if (message.applicationId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.applicationId);
        /* string project_id = 4; */
        if (message.projectId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.projectId);
        /* google.protobuf.Timestamp created_at = 5; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 6; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* repeated workflow.Step steps = 7; */
        for (let i = 0; i < message.steps.length; i++)
            Step.internalBinaryWrite(message.steps[i], writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* repeated workflow.Edge edges = 8; */
        for (let i = 0; i < message.edges.length; i++)
            Edge.internalBinaryWrite(message.edges[i], writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workflow.Workflow
 */
export const Workflow = new Workflow$Type();
