// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "dashboard/service.proto" (package "dashboard", syntax proto3)
// tslint:disable
import { DeleteWorkflowResponse } from "./workflow";
import { DeleteWorkflowRequest } from "./workflow";
import { UpdateWorkflowResponse } from "./workflow";
import { UpdateWorkflowRequest } from "./workflow";
import { CreateWorkflowResponse } from "./workflow";
import { CreateWorkflowRequest } from "./workflow";
import { GetWorkflowsResponse } from "./workflow";
import { GetWorkflowsRequest } from "./workflow";
import { DeleteEndpointResponse } from "./endpoint";
import { DeleteEndpointRequest } from "./endpoint";
import { UpdateEndpointResponse } from "./endpoint";
import { UpdateEndpointRequest } from "./endpoint";
import { CreateEndpointResponse } from "./endpoint";
import { CreateEndpointRequest } from "./endpoint";
import { GetListEndpointResponse } from "./endpoint";
import { GetListEndpointRequest } from "./endpoint";
import { DeleteApplicationResponse } from "./application";
import { DeleteApplicationRequest } from "./application";
import { UpdateApplicationResponse } from "./application";
import { UpdateApplicationRequest } from "./application";
import { CreateApplicationResponse } from "./application";
import { CreateApplicationRequest } from "./application";
import { GetListApplicationResponse } from "./application";
import { GetListApplicationRequest } from "./application";
import { DeleteProjectResponse } from "./project";
import { DeleteProjectRequest } from "./project";
import { UpdateProjectResponse } from "./project";
import { UpdateProjectRequest } from "./project";
import { CreateProjectResponse } from "./project";
import { CreateProjectRequest } from "./project";
import { GetListProjectResponse } from "./project";
import { GetListProjectRequest } from "./project";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service dashboard.DashboardService
 */
export const DashboardService = new ServiceType("dashboard.DashboardService", [
    { name: "GetListProject", options: {}, I: GetListProjectRequest, O: GetListProjectResponse },
    { name: "CreateProject", options: {}, I: CreateProjectRequest, O: CreateProjectResponse },
    { name: "UpdateProject", options: {}, I: UpdateProjectRequest, O: UpdateProjectResponse },
    { name: "DeleteProject", options: {}, I: DeleteProjectRequest, O: DeleteProjectResponse },
    { name: "GetListApplication", options: {}, I: GetListApplicationRequest, O: GetListApplicationResponse },
    { name: "CreateApplication", options: {}, I: CreateApplicationRequest, O: CreateApplicationResponse },
    { name: "UpdateApplication", options: {}, I: UpdateApplicationRequest, O: UpdateApplicationResponse },
    { name: "DeleteApplication", options: {}, I: DeleteApplicationRequest, O: DeleteApplicationResponse },
    { name: "GetListEndpoint", options: {}, I: GetListEndpointRequest, O: GetListEndpointResponse },
    { name: "CreateEndpoint", options: {}, I: CreateEndpointRequest, O: CreateEndpointResponse },
    { name: "UpdateEndpoint", options: {}, I: UpdateEndpointRequest, O: UpdateEndpointResponse },
    { name: "DeleteEndpoint", options: {}, I: DeleteEndpointRequest, O: DeleteEndpointResponse },
    { name: "GetWorkflows", options: {}, I: GetWorkflowsRequest, O: GetWorkflowsResponse },
    { name: "CreateWorkflow", options: {}, I: CreateWorkflowRequest, O: CreateWorkflowResponse },
    { name: "UpdateWorkflow", options: {}, I: UpdateWorkflowRequest, O: UpdateWorkflowResponse },
    { name: "DeleteWorkflow", options: {}, I: DeleteWorkflowRequest, O: DeleteWorkflowResponse }
]);
