// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/entrypoint/entrypoint.proto

package entrypoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntrypointType int32

const (
	EntrypointType_ENTRYPOINT_TYPE_UNSPECIFIED   EntrypointType = 0
	EntrypointType_ENTRYPOINT_TYPE_REST          EntrypointType = 1
	EntrypointType_ENTRYPOINT_TYPE_CRON          EntrypointType = 2
	EntrypointType_ENTRYPOINT_TYPE_NATS_CONSUMER EntrypointType = 3
)

// Enum value maps for EntrypointType.
var (
	EntrypointType_name = map[int32]string{
		0: "ENTRYPOINT_TYPE_UNSPECIFIED",
		1: "ENTRYPOINT_TYPE_REST",
		2: "ENTRYPOINT_TYPE_CRON",
		3: "ENTRYPOINT_TYPE_NATS_CONSUMER",
	}
	EntrypointType_value = map[string]int32{
		"ENTRYPOINT_TYPE_UNSPECIFIED":   0,
		"ENTRYPOINT_TYPE_REST":          1,
		"ENTRYPOINT_TYPE_CRON":          2,
		"ENTRYPOINT_TYPE_NATS_CONSUMER": 3,
	}
)

func (x EntrypointType) Enum() *EntrypointType {
	p := new(EntrypointType)
	*p = x
	return p
}

func (x EntrypointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntrypointType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_entrypoint_entrypoint_proto_enumTypes[0].Descriptor()
}

func (EntrypointType) Type() protoreflect.EnumType {
	return &file_core_entrypoint_entrypoint_proto_enumTypes[0]
}

func (x EntrypointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntrypointType.Descriptor instead.
func (EntrypointType) EnumDescriptor() ([]byte, []int) {
	return file_core_entrypoint_entrypoint_proto_rawDescGZIP(), []int{0}
}

type Entrypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Type          EntrypointType         `protobuf:"varint,6,opt,name=type,proto3,enum=entrypoint.EntrypointType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Setting       *Setting               `protobuf:"bytes,9,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entrypoint) Reset() {
	*x = Entrypoint{}
	mi := &file_core_entrypoint_entrypoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entrypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entrypoint) ProtoMessage() {}

func (x *Entrypoint) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_entrypoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entrypoint.ProtoReflect.Descriptor instead.
func (*Entrypoint) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_entrypoint_proto_rawDescGZIP(), []int{0}
}

func (x *Entrypoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entrypoint) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Entrypoint) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Entrypoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entrypoint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Entrypoint) GetType() EntrypointType {
	if x != nil {
		return x.Type
	}
	return EntrypointType_ENTRYPOINT_TYPE_UNSPECIFIED
}

func (x *Entrypoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entrypoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entrypoint) GetSetting() *Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type Setting struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SettingNatsConsumer *SettingNatsConsumer   `protobuf:"bytes,1,opt,name=setting_nats_consumer,json=settingNatsConsumer,proto3" json:"setting_nats_consumer,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_core_entrypoint_entrypoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_entrypoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_entrypoint_proto_rawDescGZIP(), []int{1}
}

func (x *Setting) GetSettingNatsConsumer() *SettingNatsConsumer {
	if x != nil {
		return x.SettingNatsConsumer
	}
	return nil
}

var File_core_entrypoint_entrypoint_proto protoreflect.FileDescriptor

const file_core_entrypoint_entrypoint_proto_rawDesc = "" +
	"\n" +
	" core/entrypoint/entrypoint.proto\x12\n" +
	"entrypoint\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ecore/entrypoint/settings.proto\"\xed\x02\n" +
	"\n" +
	"Entrypoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12.\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1a.entrypoint.EntrypointTypeR\x04type\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12-\n" +
	"\asetting\x18\t \x01(\v2\x13.entrypoint.SettingR\asetting\"^\n" +
	"\aSetting\x12S\n" +
	"\x15setting_nats_consumer\x18\x01 \x01(\v2\x1f.entrypoint.SettingNatsConsumerR\x13settingNatsConsumer*\x88\x01\n" +
	"\x0eEntrypointType\x12\x1f\n" +
	"\x1bENTRYPOINT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ENTRYPOINT_TYPE_REST\x10\x01\x12\x18\n" +
	"\x14ENTRYPOINT_TYPE_CRON\x10\x02\x12!\n" +
	"\x1dENTRYPOINT_TYPE_NATS_CONSUMER\x10\x03B\x9b\x01\n" +
	"\x0ecom.entrypointB\x0fEntrypointProtoP\x01Z0github.com/ideagate/model/gen-go/core/entrypoint\xa2\x02\x03EXX\xaa\x02\n" +
	"Entrypoint\xca\x02\n" +
	"Entrypoint\xe2\x02\x16Entrypoint\\GPBMetadata\xea\x02\n" +
	"Entrypointb\x06proto3"

var (
	file_core_entrypoint_entrypoint_proto_rawDescOnce sync.Once
	file_core_entrypoint_entrypoint_proto_rawDescData []byte
)

func file_core_entrypoint_entrypoint_proto_rawDescGZIP() []byte {
	file_core_entrypoint_entrypoint_proto_rawDescOnce.Do(func() {
		file_core_entrypoint_entrypoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_entrypoint_entrypoint_proto_rawDesc), len(file_core_entrypoint_entrypoint_proto_rawDesc)))
	})
	return file_core_entrypoint_entrypoint_proto_rawDescData
}

var file_core_entrypoint_entrypoint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_entrypoint_entrypoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_entrypoint_entrypoint_proto_goTypes = []any{
	(EntrypointType)(0),           // 0: entrypoint.EntrypointType
	(*Entrypoint)(nil),            // 1: entrypoint.Entrypoint
	(*Setting)(nil),               // 2: entrypoint.Setting
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*SettingNatsConsumer)(nil),   // 4: entrypoint.SettingNatsConsumer
}
var file_core_entrypoint_entrypoint_proto_depIdxs = []int32{
	3, // 0: entrypoint.Entrypoint.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: entrypoint.Entrypoint.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: entrypoint.Entrypoint.type:type_name -> entrypoint.EntrypointType
	2, // 3: entrypoint.Entrypoint.setting:type_name -> entrypoint.Setting
	4, // 4: entrypoint.Setting.setting_nats_consumer:type_name -> entrypoint.SettingNatsConsumer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_core_entrypoint_entrypoint_proto_init() }
func file_core_entrypoint_entrypoint_proto_init() {
	if File_core_entrypoint_entrypoint_proto != nil {
		return
	}
	file_core_entrypoint_settings_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_entrypoint_entrypoint_proto_rawDesc), len(file_core_entrypoint_entrypoint_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_entrypoint_entrypoint_proto_goTypes,
		DependencyIndexes: file_core_entrypoint_entrypoint_proto_depIdxs,
		EnumInfos:         file_core_entrypoint_entrypoint_proto_enumTypes,
		MessageInfos:      file_core_entrypoint_entrypoint_proto_msgTypes,
	}.Build()
	File_core_entrypoint_entrypoint_proto = out.File
	file_core_entrypoint_entrypoint_proto_goTypes = nil
	file_core_entrypoint_entrypoint_proto_depIdxs = nil
}
