// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/entrypoint/settings.proto

package entrypoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingNatsConsumer struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DependencyEndpointId string                 `protobuf:"bytes,1,opt,name=dependency_endpoint_id,json=dependencyEndpointId,proto3" json:"dependency_endpoint_id,omitempty"`
	ConsumerName         string                 `protobuf:"bytes,2,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SettingNatsConsumer) Reset() {
	*x = SettingNatsConsumer{}
	mi := &file_core_entrypoint_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingNatsConsumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingNatsConsumer) ProtoMessage() {}

func (x *SettingNatsConsumer) ProtoReflect() protoreflect.Message {
	mi := &file_core_entrypoint_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingNatsConsumer.ProtoReflect.Descriptor instead.
func (*SettingNatsConsumer) Descriptor() ([]byte, []int) {
	return file_core_entrypoint_settings_proto_rawDescGZIP(), []int{0}
}

func (x *SettingNatsConsumer) GetDependencyEndpointId() string {
	if x != nil {
		return x.DependencyEndpointId
	}
	return ""
}

func (x *SettingNatsConsumer) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

var File_core_entrypoint_settings_proto protoreflect.FileDescriptor

const file_core_entrypoint_settings_proto_rawDesc = "" +
	"\n" +
	"\x1ecore/entrypoint/settings.proto\x12\n" +
	"entrypoint\"p\n" +
	"\x13SettingNatsConsumer\x124\n" +
	"\x16dependency_endpoint_id\x18\x01 \x01(\tR\x14dependencyEndpointId\x12#\n" +
	"\rconsumer_name\x18\x02 \x01(\tR\fconsumerNameB\x99\x01\n" +
	"\x0ecom.entrypointB\rSettingsProtoP\x01Z0github.com/ideagate/model/gen-go/core/entrypoint\xa2\x02\x03EXX\xaa\x02\n" +
	"Entrypoint\xca\x02\n" +
	"Entrypoint\xe2\x02\x16Entrypoint\\GPBMetadata\xea\x02\n" +
	"Entrypointb\x06proto3"

var (
	file_core_entrypoint_settings_proto_rawDescOnce sync.Once
	file_core_entrypoint_settings_proto_rawDescData []byte
)

func file_core_entrypoint_settings_proto_rawDescGZIP() []byte {
	file_core_entrypoint_settings_proto_rawDescOnce.Do(func() {
		file_core_entrypoint_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_entrypoint_settings_proto_rawDesc), len(file_core_entrypoint_settings_proto_rawDesc)))
	})
	return file_core_entrypoint_settings_proto_rawDescData
}

var file_core_entrypoint_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_entrypoint_settings_proto_goTypes = []any{
	(*SettingNatsConsumer)(nil), // 0: entrypoint.SettingNatsConsumer
}
var file_core_entrypoint_settings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_entrypoint_settings_proto_init() }
func file_core_entrypoint_settings_proto_init() {
	if File_core_entrypoint_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_entrypoint_settings_proto_rawDesc), len(file_core_entrypoint_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_entrypoint_settings_proto_goTypes,
		DependencyIndexes: file_core_entrypoint_settings_proto_depIdxs,
		MessageInfos:      file_core_entrypoint_settings_proto_msgTypes,
	}.Build()
	File_core_entrypoint_settings_proto = out.File
	file_core_entrypoint_settings_proto_goTypes = nil
	file_core_entrypoint_settings_proto_depIdxs = nil
}
