// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core/endpoint/endpoint.proto

package endpoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointType int32

const (
	EndpointType_ENDPOINT_TYPE_UNSPECIFIED EndpointType = 0
	EndpointType_ENDPOINT_TYPE_REST        EndpointType = 1
	EndpointType_ENDPOINT_TYPE_CRON        EndpointType = 2
)

// Enum value maps for EndpointType.
var (
	EndpointType_name = map[int32]string{
		0: "ENDPOINT_TYPE_UNSPECIFIED",
		1: "ENDPOINT_TYPE_REST",
		2: "ENDPOINT_TYPE_CRON",
	}
	EndpointType_value = map[string]int32{
		"ENDPOINT_TYPE_UNSPECIFIED": 0,
		"ENDPOINT_TYPE_REST":        1,
		"ENDPOINT_TYPE_CRON":        2,
	}
)

func (x EndpointType) Enum() *EndpointType {
	p := new(EndpointType)
	*p = x
	return p
}

func (x EndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_endpoint_endpoint_proto_enumTypes[0].Descriptor()
}

func (EndpointType) Type() protoreflect.EnumType {
	return &file_core_endpoint_endpoint_proto_enumTypes[0]
}

func (x EndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointType.Descriptor instead.
func (EndpointType) EnumDescriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{0}
}

type VariableType int32

const (
	VariableType_VARIABLE_TYPE_UNSPECIFIED VariableType = 0
	VariableType_VARIABLE_TYPE_STRING      VariableType = 1
	VariableType_VARIABLE_TYPE_INT         VariableType = 2
	VariableType_VARIABLE_TYPE_FLOAT       VariableType = 3
	VariableType_VARIABLE_TYPE_BOOL        VariableType = 4
	VariableType_VARIABLE_TYPE_OBJECT      VariableType = 5
)

// Enum value maps for VariableType.
var (
	VariableType_name = map[int32]string{
		0: "VARIABLE_TYPE_UNSPECIFIED",
		1: "VARIABLE_TYPE_STRING",
		2: "VARIABLE_TYPE_INT",
		3: "VARIABLE_TYPE_FLOAT",
		4: "VARIABLE_TYPE_BOOL",
		5: "VARIABLE_TYPE_OBJECT",
	}
	VariableType_value = map[string]int32{
		"VARIABLE_TYPE_UNSPECIFIED": 0,
		"VARIABLE_TYPE_STRING":      1,
		"VARIABLE_TYPE_INT":         2,
		"VARIABLE_TYPE_FLOAT":       3,
		"VARIABLE_TYPE_BOOL":        4,
		"VARIABLE_TYPE_OBJECT":      5,
	}
)

func (x VariableType) Enum() *VariableType {
	p := new(VariableType)
	*p = x
	return p
}

func (x VariableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariableType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_endpoint_endpoint_proto_enumTypes[1].Descriptor()
}

func (VariableType) Type() protoreflect.EnumType {
	return &file_core_endpoint_endpoint_proto_enumTypes[1]
}

func (x VariableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariableType.Descriptor instead.
func (VariableType) EnumDescriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{1}
}

type StepType int32

const (
	StepType_STEP_TYPE_UNSPECIFIED StepType = 0
	StepType_STEP_TYPE_START       StepType = 1
	StepType_STEP_TYPE_END         StepType = 2
	StepType_STEP_TYPE_SLEEP       StepType = 3
	StepType_STEP_TYPE_SCRIPT_JS   StepType = 4
	StepType_STEP_TYPE_CONDITION   StepType = 5
	StepType_STEP_TYPE_REST        StepType = 6
	StepType_STEP_TYPE_MYSQL       StepType = 7
	StepType_STEP_TYPE_POSTGRESQL  StepType = 8
	StepType_STEP_TYPE_REDIS       StepType = 9
)

// Enum value maps for StepType.
var (
	StepType_name = map[int32]string{
		0: "STEP_TYPE_UNSPECIFIED",
		1: "STEP_TYPE_START",
		2: "STEP_TYPE_END",
		3: "STEP_TYPE_SLEEP",
		4: "STEP_TYPE_SCRIPT_JS",
		5: "STEP_TYPE_CONDITION",
		6: "STEP_TYPE_REST",
		7: "STEP_TYPE_MYSQL",
		8: "STEP_TYPE_POSTGRESQL",
		9: "STEP_TYPE_REDIS",
	}
	StepType_value = map[string]int32{
		"STEP_TYPE_UNSPECIFIED": 0,
		"STEP_TYPE_START":       1,
		"STEP_TYPE_END":         2,
		"STEP_TYPE_SLEEP":       3,
		"STEP_TYPE_SCRIPT_JS":   4,
		"STEP_TYPE_CONDITION":   5,
		"STEP_TYPE_REST":        6,
		"STEP_TYPE_MYSQL":       7,
		"STEP_TYPE_POSTGRESQL":  8,
		"STEP_TYPE_REDIS":       9,
	}
)

func (x StepType) Enum() *StepType {
	p := new(StepType)
	*p = x
	return p
}

func (x StepType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_endpoint_endpoint_proto_enumTypes[2].Descriptor()
}

func (StepType) Type() protoreflect.EnumType {
	return &file_core_endpoint_endpoint_proto_enumTypes[2]
}

func (x StepType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepType.Descriptor instead.
func (StepType) EnumDescriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{2}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Type          EndpointType           `protobuf:"varint,6,opt,name=type,proto3,enum=endpoint.EndpointType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*Endpoint_SettingRest
	//	*Endpoint_SettingCron
	Settings      isEndpoint_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Endpoint) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Endpoint) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Endpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Endpoint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Endpoint) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Endpoint) GetSettings() isEndpoint_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Endpoint) GetSettingRest() *SettingRest {
	if x != nil {
		if x, ok := x.Settings.(*Endpoint_SettingRest); ok {
			return x.SettingRest
		}
	}
	return nil
}

func (x *Endpoint) GetSettingCron() *SettingCron {
	if x != nil {
		if x, ok := x.Settings.(*Endpoint_SettingCron); ok {
			return x.SettingCron
		}
	}
	return nil
}

type isEndpoint_Settings interface {
	isEndpoint_Settings()
}

type Endpoint_SettingRest struct {
	SettingRest *SettingRest `protobuf:"bytes,101,opt,name=setting_rest,json=settingRest,proto3,oneof"`
}

type Endpoint_SettingCron struct {
	SettingCron *SettingCron `protobuf:"bytes,102,opt,name=setting_cron,json=settingCron,proto3,oneof"`
}

func (*Endpoint_SettingRest) isEndpoint_Settings() {}

func (*Endpoint_SettingCron) isEndpoint_Settings() {}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          VariableType           `protobuf:"varint,1,opt,name=type,proto3,enum=endpoint.VariableType" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *Variable) GetType() VariableType {
	if x != nil {
		return x.Type
	}
	return VariableType_VARIABLE_TYPE_UNSPECIFIED
}

func (x *Variable) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Variable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Variable) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

type SettingRest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	NumWorkers    int32                  `protobuf:"varint,4,opt,name=num_workers,json=numWorkers,proto3" json:"num_workers,omitempty"`
	Query         map[string]*Variable   `protobuf:"bytes,5,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Json          map[string]*Variable   `protobuf:"bytes,6,rep,name=json,proto3" json:"json,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingRest) Reset() {
	*x = SettingRest{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingRest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingRest) ProtoMessage() {}

func (x *SettingRest) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingRest.ProtoReflect.Descriptor instead.
func (*SettingRest) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *SettingRest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SettingRest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SettingRest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SettingRest) GetNumWorkers() int32 {
	if x != nil {
		return x.NumWorkers
	}
	return 0
}

func (x *SettingRest) GetQuery() map[string]*Variable {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SettingRest) GetJson() map[string]*Variable {
	if x != nil {
		return x.Json
	}
	return nil
}

type SettingCron struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cron          string                 `protobuf:"bytes,1,opt,name=cron,proto3" json:"cron,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingCron) Reset() {
	*x = SettingCron{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingCron) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingCron) ProtoMessage() {}

func (x *SettingCron) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingCron.ProtoReflect.Descriptor instead.
func (*SettingCron) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *SettingCron) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *SettingCron) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*Step                `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *Workflow) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Workflow) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          StepType               `protobuf:"varint,3,opt,name=type,proto3,enum=endpoint.StepType" json:"type,omitempty"`
	Variables     map[string]*Variable   `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Action        *Action                `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Outputs       map[string]*Variable   `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Returns       []*Return              `protobuf:"bytes,7,rep,name=returns,proto3" json:"returns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetType() StepType {
	if x != nil {
		return x.Type
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (x *Step) GetVariables() map[string]*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Step) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Step) GetOutputs() map[string]*Variable {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Step) GetReturns() []*Return {
	if x != nil {
		return x.Returns
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataSourceId  string                 `protobuf:"bytes,1,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	End           *ActionEnd             `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Mysql         *ActionMysql           `protobuf:"bytes,3,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Rest          *ActionRest            `protobuf:"bytes,4,opt,name=rest,proto3" json:"rest,omitempty"`
	Sleep         *ActionSleep           `protobuf:"bytes,5,opt,name=sleep,proto3" json:"sleep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *Action) GetDataSourceId() string {
	if x != nil {
		return x.DataSourceId
	}
	return ""
}

func (x *Action) GetEnd() *ActionEnd {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Action) GetMysql() *ActionMysql {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Action) GetRest() *ActionRest {
	if x != nil {
		return x.Rest
	}
	return nil
}

func (x *Action) GetSleep() *ActionSleep {
	if x != nil {
		return x.Sleep
	}
	return nil
}

type ActionEnd struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReturnDataFromStepIds []string               `protobuf:"bytes,1,rep,name=return_data_from_step_ids,json=returnDataFromStepIds,proto3" json:"return_data_from_step_ids,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ActionEnd) Reset() {
	*x = ActionEnd{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEnd) ProtoMessage() {}

func (x *ActionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEnd.ProtoReflect.Descriptor instead.
func (*ActionEnd) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *ActionEnd) GetReturnDataFromStepIds() []string {
	if x != nil {
		return x.ReturnDataFromStepIds
	}
	return nil
}

type ActionMysql struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*Query               `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionMysql) Reset() {
	*x = ActionMysql{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionMysql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionMysql) ProtoMessage() {}

func (x *ActionMysql) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionMysql.ProtoReflect.Descriptor instead.
func (*ActionMysql) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *ActionMysql) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

type ActionRest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *Variable              `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]*Variable   `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestType   string                 `protobuf:"bytes,4,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	RequestBody   string                 `protobuf:"bytes,5,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRest) Reset() {
	*x = ActionRest{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRest) ProtoMessage() {}

func (x *ActionRest) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRest.ProtoReflect.Descriptor instead.
func (*ActionRest) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *ActionRest) GetPath() *Variable {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *ActionRest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ActionRest) GetHeaders() map[string]*Variable {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ActionRest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *ActionRest) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

type ActionSleep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs     int64                  `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSleep) Reset() {
	*x = ActionSleep{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSleep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSleep) ProtoMessage() {}

func (x *ActionSleep) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSleep.ProtoReflect.Descriptor instead.
func (*ActionSleep) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{10}
}

func (x *ActionSleep) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Variable              `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Parameters    []*Variable            `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{11}
}

func (x *Query) GetQuery() *Variable {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Query) GetParameters() []*Variable {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Return struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsFinishCondition string                 `protobuf:"bytes,3,opt,name=is_finish_condition,json=isFinishCondition,proto3" json:"is_finish_condition,omitempty"`
	NextStepId        string                 `protobuf:"bytes,4,opt,name=next_step_id,json=nextStepId,proto3" json:"next_step_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Return) Reset() {
	*x = Return{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return) ProtoMessage() {}

func (x *Return) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return.ProtoReflect.Descriptor instead.
func (*Return) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{12}
}

func (x *Return) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Return) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Return) GetIsFinishCondition() string {
	if x != nil {
		return x.IsFinishCondition
	}
	return ""
}

func (x *Return) GetNextStepId() string {
	if x != nil {
		return x.NextStepId
	}
	return ""
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConditionId   string                 `protobuf:"bytes,2,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Dest          string                 `protobuf:"bytes,4,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{13}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetConditionId() string {
	if x != nil {
		return x.ConditionId
	}
	return ""
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

var File_core_endpoint_endpoint_proto protoreflect.FileDescriptor

const file_core_endpoint_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x1ccore/endpoint/endpoint.proto\x12\bendpoint\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x03\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12*\n" +
	"\x04type\x18\x06 \x01(\x0e2\x16.endpoint.EndpointTypeR\x04type\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12:\n" +
	"\fsetting_rest\x18e \x01(\v2\x15.endpoint.SettingRestH\x00R\vsettingRest\x12:\n" +
	"\fsetting_cron\x18f \x01(\v2\x15.endpoint.SettingCronH\x00R\vsettingCronB\n" +
	"\n" +
	"\bsettings\"\x82\x01\n" +
	"\bVariable\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.endpoint.VariableTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\"\x81\x03\n" +
	"\vSettingRest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vnum_workers\x18\x04 \x01(\x05R\n" +
	"numWorkers\x126\n" +
	"\x05query\x18\x05 \x03(\v2 .endpoint.SettingRest.QueryEntryR\x05query\x123\n" +
	"\x04json\x18\x06 \x03(\v2\x1f.endpoint.SettingRest.JsonEntryR\x04json\x1aL\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\x1aK\n" +
	"\tJsonEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\"@\n" +
	"\vSettingCron\x12\x12\n" +
	"\x04cron\x18\x01 \x01(\tR\x04cron\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"V\n" +
	"\bWorkflow\x12$\n" +
	"\x05steps\x18\x01 \x03(\v2\x0e.endpoint.StepR\x05steps\x12$\n" +
	"\x05edges\x18\x02 \x03(\v2\x0e.endpoint.EdgeR\x05edges\"\xbe\x03\n" +
	"\x04Step\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.endpoint.StepTypeR\x04type\x12;\n" +
	"\tvariables\x18\x04 \x03(\v2\x1d.endpoint.Step.VariablesEntryR\tvariables\x12(\n" +
	"\x06action\x18\x05 \x01(\v2\x10.endpoint.ActionR\x06action\x125\n" +
	"\aoutputs\x18\x06 \x03(\v2\x1b.endpoint.Step.OutputsEntryR\aoutputs\x12*\n" +
	"\areturns\x18\a \x03(\v2\x10.endpoint.ReturnR\areturns\x1aP\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\x1aN\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x06Action\x12$\n" +
	"\x0edata_source_id\x18\x01 \x01(\tR\fdataSourceId\x12%\n" +
	"\x03end\x18\x02 \x01(\v2\x13.endpoint.ActionEndR\x03end\x12+\n" +
	"\x05mysql\x18\x03 \x01(\v2\x15.endpoint.ActionMysqlR\x05mysql\x12(\n" +
	"\x04rest\x18\x04 \x01(\v2\x14.endpoint.ActionRestR\x04rest\x12+\n" +
	"\x05sleep\x18\x05 \x01(\v2\x15.endpoint.ActionSleepR\x05sleep\"E\n" +
	"\tActionEnd\x128\n" +
	"\x19return_data_from_step_ids\x18\x01 \x03(\tR\x15returnDataFromStepIds\"8\n" +
	"\vActionMysql\x12)\n" +
	"\aqueries\x18\x01 \x03(\v2\x0f.endpoint.QueryR\aqueries\"\x9f\x02\n" +
	"\n" +
	"ActionRest\x12&\n" +
	"\x04path\x18\x01 \x01(\v2\x12.endpoint.VariableR\x04path\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12;\n" +
	"\aheaders\x18\x03 \x03(\v2!.endpoint.ActionRest.HeadersEntryR\aheaders\x12!\n" +
	"\frequest_type\x18\x04 \x01(\tR\vrequestType\x12!\n" +
	"\frequest_body\x18\x05 \x01(\tR\vrequestBody\x1aN\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\",\n" +
	"\vActionSleep\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x03R\ttimeoutMs\"e\n" +
	"\x05Query\x12(\n" +
	"\x05query\x18\x01 \x01(\v2\x12.endpoint.VariableR\x05query\x122\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x12.endpoint.VariableR\n" +
	"parameters\"~\n" +
	"\x06Return\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13is_finish_condition\x18\x03 \x01(\tR\x11isFinishCondition\x12 \n" +
	"\fnext_step_id\x18\x04 \x01(\tR\n" +
	"nextStepId\"e\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcondition_id\x18\x02 \x01(\tR\vconditionId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04dest\x18\x04 \x01(\tR\x04dest*]\n" +
	"\fEndpointType\x12\x1d\n" +
	"\x19ENDPOINT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENDPOINT_TYPE_REST\x10\x01\x12\x16\n" +
	"\x12ENDPOINT_TYPE_CRON\x10\x02*\xa9\x01\n" +
	"\fVariableType\x12\x1d\n" +
	"\x19VARIABLE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14VARIABLE_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11VARIABLE_TYPE_INT\x10\x02\x12\x17\n" +
	"\x13VARIABLE_TYPE_FLOAT\x10\x03\x12\x16\n" +
	"\x12VARIABLE_TYPE_BOOL\x10\x04\x12\x18\n" +
	"\x14VARIABLE_TYPE_OBJECT\x10\x05*\xec\x01\n" +
	"\bStepType\x12\x19\n" +
	"\x15STEP_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTEP_TYPE_START\x10\x01\x12\x11\n" +
	"\rSTEP_TYPE_END\x10\x02\x12\x13\n" +
	"\x0fSTEP_TYPE_SLEEP\x10\x03\x12\x17\n" +
	"\x13STEP_TYPE_SCRIPT_JS\x10\x04\x12\x17\n" +
	"\x13STEP_TYPE_CONDITION\x10\x05\x12\x12\n" +
	"\x0eSTEP_TYPE_REST\x10\x06\x12\x13\n" +
	"\x0fSTEP_TYPE_MYSQL\x10\a\x12\x18\n" +
	"\x14STEP_TYPE_POSTGRESQL\x10\b\x12\x13\n" +
	"\x0fSTEP_TYPE_REDIS\x10\tB\xa1\x01\n" +
	"\fcom.endpointB\rEndpointProtoP\x01ZBgithub.com/bayu-aditya/ideagate/backend/model/gen-go/core/endpoint\xa2\x02\x03EXX\xaa\x02\bEndpoint\xca\x02\bEndpoint\xe2\x02\x14Endpoint\\GPBMetadata\xea\x02\bEndpointb\x06proto3"

var (
	file_core_endpoint_endpoint_proto_rawDescOnce sync.Once
	file_core_endpoint_endpoint_proto_rawDescData []byte
)

func file_core_endpoint_endpoint_proto_rawDescGZIP() []byte {
	file_core_endpoint_endpoint_proto_rawDescOnce.Do(func() {
		file_core_endpoint_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_endpoint_endpoint_proto_rawDesc), len(file_core_endpoint_endpoint_proto_rawDesc)))
	})
	return file_core_endpoint_endpoint_proto_rawDescData
}

var file_core_endpoint_endpoint_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_core_endpoint_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_core_endpoint_endpoint_proto_goTypes = []any{
	(EndpointType)(0),             // 0: endpoint.EndpointType
	(VariableType)(0),             // 1: endpoint.VariableType
	(StepType)(0),                 // 2: endpoint.StepType
	(*Endpoint)(nil),              // 3: endpoint.Endpoint
	(*Variable)(nil),              // 4: endpoint.Variable
	(*SettingRest)(nil),           // 5: endpoint.SettingRest
	(*SettingCron)(nil),           // 6: endpoint.SettingCron
	(*Workflow)(nil),              // 7: endpoint.Workflow
	(*Step)(nil),                  // 8: endpoint.Step
	(*Action)(nil),                // 9: endpoint.Action
	(*ActionEnd)(nil),             // 10: endpoint.ActionEnd
	(*ActionMysql)(nil),           // 11: endpoint.ActionMysql
	(*ActionRest)(nil),            // 12: endpoint.ActionRest
	(*ActionSleep)(nil),           // 13: endpoint.ActionSleep
	(*Query)(nil),                 // 14: endpoint.Query
	(*Return)(nil),                // 15: endpoint.Return
	(*Edge)(nil),                  // 16: endpoint.Edge
	nil,                           // 17: endpoint.SettingRest.QueryEntry
	nil,                           // 18: endpoint.SettingRest.JsonEntry
	nil,                           // 19: endpoint.Step.VariablesEntry
	nil,                           // 20: endpoint.Step.OutputsEntry
	nil,                           // 21: endpoint.ActionRest.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_core_endpoint_endpoint_proto_depIdxs = []int32{
	22, // 0: endpoint.Endpoint.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: endpoint.Endpoint.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: endpoint.Endpoint.type:type_name -> endpoint.EndpointType
	5,  // 3: endpoint.Endpoint.setting_rest:type_name -> endpoint.SettingRest
	6,  // 4: endpoint.Endpoint.setting_cron:type_name -> endpoint.SettingCron
	1,  // 5: endpoint.Variable.type:type_name -> endpoint.VariableType
	17, // 6: endpoint.SettingRest.query:type_name -> endpoint.SettingRest.QueryEntry
	18, // 7: endpoint.SettingRest.json:type_name -> endpoint.SettingRest.JsonEntry
	8,  // 8: endpoint.Workflow.steps:type_name -> endpoint.Step
	16, // 9: endpoint.Workflow.edges:type_name -> endpoint.Edge
	2,  // 10: endpoint.Step.type:type_name -> endpoint.StepType
	19, // 11: endpoint.Step.variables:type_name -> endpoint.Step.VariablesEntry
	9,  // 12: endpoint.Step.action:type_name -> endpoint.Action
	20, // 13: endpoint.Step.outputs:type_name -> endpoint.Step.OutputsEntry
	15, // 14: endpoint.Step.returns:type_name -> endpoint.Return
	10, // 15: endpoint.Action.end:type_name -> endpoint.ActionEnd
	11, // 16: endpoint.Action.mysql:type_name -> endpoint.ActionMysql
	12, // 17: endpoint.Action.rest:type_name -> endpoint.ActionRest
	13, // 18: endpoint.Action.sleep:type_name -> endpoint.ActionSleep
	14, // 19: endpoint.ActionMysql.queries:type_name -> endpoint.Query
	4,  // 20: endpoint.ActionRest.path:type_name -> endpoint.Variable
	21, // 21: endpoint.ActionRest.headers:type_name -> endpoint.ActionRest.HeadersEntry
	4,  // 22: endpoint.Query.query:type_name -> endpoint.Variable
	4,  // 23: endpoint.Query.parameters:type_name -> endpoint.Variable
	4,  // 24: endpoint.SettingRest.QueryEntry.value:type_name -> endpoint.Variable
	4,  // 25: endpoint.SettingRest.JsonEntry.value:type_name -> endpoint.Variable
	4,  // 26: endpoint.Step.VariablesEntry.value:type_name -> endpoint.Variable
	4,  // 27: endpoint.Step.OutputsEntry.value:type_name -> endpoint.Variable
	4,  // 28: endpoint.ActionRest.HeadersEntry.value:type_name -> endpoint.Variable
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_core_endpoint_endpoint_proto_init() }
func file_core_endpoint_endpoint_proto_init() {
	if File_core_endpoint_endpoint_proto != nil {
		return
	}
	file_core_endpoint_endpoint_proto_msgTypes[0].OneofWrappers = []any{
		(*Endpoint_SettingRest)(nil),
		(*Endpoint_SettingCron)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_endpoint_endpoint_proto_rawDesc), len(file_core_endpoint_endpoint_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_endpoint_endpoint_proto_goTypes,
		DependencyIndexes: file_core_endpoint_endpoint_proto_depIdxs,
		EnumInfos:         file_core_endpoint_endpoint_proto_enumTypes,
		MessageInfos:      file_core_endpoint_endpoint_proto_msgTypes,
	}.Build()
	File_core_endpoint_endpoint_proto = out.File
	file_core_endpoint_endpoint_proto_goTypes = nil
	file_core_endpoint_endpoint_proto_depIdxs = nil
}
