// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core/endpoint/endpoint.proto

package endpoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointType int32

const (
	EndpointType_ENDPOINT_TYPE_UNSPECIFIED EndpointType = 0
	EndpointType_ENDPOINT_TYPE_REST        EndpointType = 1
	EndpointType_ENDPOINT_TYPE_CRON        EndpointType = 2
)

// Enum value maps for EndpointType.
var (
	EndpointType_name = map[int32]string{
		0: "ENDPOINT_TYPE_UNSPECIFIED",
		1: "ENDPOINT_TYPE_REST",
		2: "ENDPOINT_TYPE_CRON",
	}
	EndpointType_value = map[string]int32{
		"ENDPOINT_TYPE_UNSPECIFIED": 0,
		"ENDPOINT_TYPE_REST":        1,
		"ENDPOINT_TYPE_CRON":        2,
	}
)

func (x EndpointType) Enum() *EndpointType {
	p := new(EndpointType)
	*p = x
	return p
}

func (x EndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_endpoint_endpoint_proto_enumTypes[0].Descriptor()
}

func (EndpointType) Type() protoreflect.EnumType {
	return &file_core_endpoint_endpoint_proto_enumTypes[0]
}

func (x EndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointType.Descriptor instead.
func (EndpointType) EnumDescriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{0}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Type          EndpointType           `protobuf:"varint,6,opt,name=type,proto3,enum=endpoint.EndpointType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Rollout:
	//
	//	*Endpoint_BlueGreen
	//	*Endpoint_Canary
	Rollout isEndpoint_Rollout `protobuf_oneof:"rollout"`
	// Types that are valid to be assigned to Settings:
	//
	//	*Endpoint_SettingRest
	//	*Endpoint_SettingCron
	Settings      isEndpoint_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Endpoint) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Endpoint) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Endpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Endpoint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Endpoint) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Endpoint) GetRollout() isEndpoint_Rollout {
	if x != nil {
		return x.Rollout
	}
	return nil
}

func (x *Endpoint) GetBlueGreen() *RolloutBlueGreen {
	if x != nil {
		if x, ok := x.Rollout.(*Endpoint_BlueGreen); ok {
			return x.BlueGreen
		}
	}
	return nil
}

func (x *Endpoint) GetCanary() *RolloutCanary {
	if x != nil {
		if x, ok := x.Rollout.(*Endpoint_Canary); ok {
			return x.Canary
		}
	}
	return nil
}

func (x *Endpoint) GetSettings() isEndpoint_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Endpoint) GetSettingRest() *SettingRest {
	if x != nil {
		if x, ok := x.Settings.(*Endpoint_SettingRest); ok {
			return x.SettingRest
		}
	}
	return nil
}

func (x *Endpoint) GetSettingCron() *SettingCron {
	if x != nil {
		if x, ok := x.Settings.(*Endpoint_SettingCron); ok {
			return x.SettingCron
		}
	}
	return nil
}

type isEndpoint_Rollout interface {
	isEndpoint_Rollout()
}

type Endpoint_BlueGreen struct {
	BlueGreen *RolloutBlueGreen `protobuf:"bytes,91,opt,name=blue_green,json=blueGreen,proto3,oneof"`
}

type Endpoint_Canary struct {
	Canary *RolloutCanary `protobuf:"bytes,92,opt,name=canary,proto3,oneof"`
}

func (*Endpoint_BlueGreen) isEndpoint_Rollout() {}

func (*Endpoint_Canary) isEndpoint_Rollout() {}

type isEndpoint_Settings interface {
	isEndpoint_Settings()
}

type Endpoint_SettingRest struct {
	SettingRest *SettingRest `protobuf:"bytes,101,opt,name=setting_rest,json=settingRest,proto3,oneof"`
}

type Endpoint_SettingCron struct {
	SettingCron *SettingCron `protobuf:"bytes,102,opt,name=setting_cron,json=settingCron,proto3,oneof"`
}

func (*Endpoint_SettingRest) isEndpoint_Settings() {}

func (*Endpoint_SettingCron) isEndpoint_Settings() {}

type SettingRest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	NumWorkers    int32                  `protobuf:"varint,4,opt,name=num_workers,json=numWorkers,proto3" json:"num_workers,omitempty"`
	Query         map[string]*Variable   `protobuf:"bytes,5,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Json          map[string]*Variable   `protobuf:"bytes,6,rep,name=json,proto3" json:"json,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingRest) Reset() {
	*x = SettingRest{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingRest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingRest) ProtoMessage() {}

func (x *SettingRest) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingRest.ProtoReflect.Descriptor instead.
func (*SettingRest) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *SettingRest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SettingRest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SettingRest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SettingRest) GetNumWorkers() int32 {
	if x != nil {
		return x.NumWorkers
	}
	return 0
}

func (x *SettingRest) GetQuery() map[string]*Variable {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SettingRest) GetJson() map[string]*Variable {
	if x != nil {
		return x.Json
	}
	return nil
}

type SettingCron struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cron          string                 `protobuf:"bytes,1,opt,name=cron,proto3" json:"cron,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingCron) Reset() {
	*x = SettingCron{}
	mi := &file_core_endpoint_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingCron) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingCron) ProtoMessage() {}

func (x *SettingCron) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingCron.ProtoReflect.Descriptor instead.
func (*SettingCron) Descriptor() ([]byte, []int) {
	return file_core_endpoint_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *SettingCron) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *SettingCron) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

var File_core_endpoint_endpoint_proto protoreflect.FileDescriptor

const file_core_endpoint_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x1ccore/endpoint/endpoint.proto\x12\bendpoint\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ccore/endpoint/variable.proto\x1a\x1bcore/endpoint/rollout.proto\"\xb7\x04\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12*\n" +
	"\x04type\x18\x06 \x01(\x0e2\x16.endpoint.EndpointTypeR\x04type\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12;\n" +
	"\n" +
	"blue_green\x18[ \x01(\v2\x1a.endpoint.RolloutBlueGreenH\x00R\tblueGreen\x121\n" +
	"\x06canary\x18\\ \x01(\v2\x17.endpoint.RolloutCanaryH\x00R\x06canary\x12:\n" +
	"\fsetting_rest\x18e \x01(\v2\x15.endpoint.SettingRestH\x01R\vsettingRest\x12:\n" +
	"\fsetting_cron\x18f \x01(\v2\x15.endpoint.SettingCronH\x01R\vsettingCronB\t\n" +
	"\arolloutB\n" +
	"\n" +
	"\bsettings\"\x81\x03\n" +
	"\vSettingRest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vnum_workers\x18\x04 \x01(\x05R\n" +
	"numWorkers\x126\n" +
	"\x05query\x18\x05 \x03(\v2 .endpoint.SettingRest.QueryEntryR\x05query\x123\n" +
	"\x04json\x18\x06 \x03(\v2\x1f.endpoint.SettingRest.JsonEntryR\x04json\x1aL\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\x1aK\n" +
	"\tJsonEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\"@\n" +
	"\vSettingCron\x12\x12\n" +
	"\x04cron\x18\x01 \x01(\tR\x04cron\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs*]\n" +
	"\fEndpointType\x12\x1d\n" +
	"\x19ENDPOINT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENDPOINT_TYPE_REST\x10\x01\x12\x16\n" +
	"\x12ENDPOINT_TYPE_CRON\x10\x02B\x8d\x01\n" +
	"\fcom.endpointB\rEndpointProtoP\x01Z.github.com/ideagate/model/gen-go/core/endpoint\xa2\x02\x03EXX\xaa\x02\bEndpoint\xca\x02\bEndpoint\xe2\x02\x14Endpoint\\GPBMetadata\xea\x02\bEndpointb\x06proto3"

var (
	file_core_endpoint_endpoint_proto_rawDescOnce sync.Once
	file_core_endpoint_endpoint_proto_rawDescData []byte
)

func file_core_endpoint_endpoint_proto_rawDescGZIP() []byte {
	file_core_endpoint_endpoint_proto_rawDescOnce.Do(func() {
		file_core_endpoint_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_endpoint_endpoint_proto_rawDesc), len(file_core_endpoint_endpoint_proto_rawDesc)))
	})
	return file_core_endpoint_endpoint_proto_rawDescData
}

var file_core_endpoint_endpoint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_endpoint_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_core_endpoint_endpoint_proto_goTypes = []any{
	(EndpointType)(0),             // 0: endpoint.EndpointType
	(*Endpoint)(nil),              // 1: endpoint.Endpoint
	(*SettingRest)(nil),           // 2: endpoint.SettingRest
	(*SettingCron)(nil),           // 3: endpoint.SettingCron
	nil,                           // 4: endpoint.SettingRest.QueryEntry
	nil,                           // 5: endpoint.SettingRest.JsonEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*RolloutBlueGreen)(nil),      // 7: endpoint.RolloutBlueGreen
	(*RolloutCanary)(nil),         // 8: endpoint.RolloutCanary
	(*Variable)(nil),              // 9: endpoint.Variable
}
var file_core_endpoint_endpoint_proto_depIdxs = []int32{
	6,  // 0: endpoint.Endpoint.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: endpoint.Endpoint.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: endpoint.Endpoint.type:type_name -> endpoint.EndpointType
	7,  // 3: endpoint.Endpoint.blue_green:type_name -> endpoint.RolloutBlueGreen
	8,  // 4: endpoint.Endpoint.canary:type_name -> endpoint.RolloutCanary
	2,  // 5: endpoint.Endpoint.setting_rest:type_name -> endpoint.SettingRest
	3,  // 6: endpoint.Endpoint.setting_cron:type_name -> endpoint.SettingCron
	4,  // 7: endpoint.SettingRest.query:type_name -> endpoint.SettingRest.QueryEntry
	5,  // 8: endpoint.SettingRest.json:type_name -> endpoint.SettingRest.JsonEntry
	9,  // 9: endpoint.SettingRest.QueryEntry.value:type_name -> endpoint.Variable
	9,  // 10: endpoint.SettingRest.JsonEntry.value:type_name -> endpoint.Variable
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_core_endpoint_endpoint_proto_init() }
func file_core_endpoint_endpoint_proto_init() {
	if File_core_endpoint_endpoint_proto != nil {
		return
	}
	file_core_endpoint_variable_proto_init()
	file_core_endpoint_rollout_proto_init()
	file_core_endpoint_endpoint_proto_msgTypes[0].OneofWrappers = []any{
		(*Endpoint_BlueGreen)(nil),
		(*Endpoint_Canary)(nil),
		(*Endpoint_SettingRest)(nil),
		(*Endpoint_SettingCron)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_endpoint_endpoint_proto_rawDesc), len(file_core_endpoint_endpoint_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_endpoint_endpoint_proto_goTypes,
		DependencyIndexes: file_core_endpoint_endpoint_proto_depIdxs,
		EnumInfos:         file_core_endpoint_endpoint_proto_enumTypes,
		MessageInfos:      file_core_endpoint_endpoint_proto_msgTypes,
	}.Build()
	File_core_endpoint_endpoint_proto = out.File
	file_core_endpoint_endpoint_proto_goTypes = nil
	file_core_endpoint_endpoint_proto_depIdxs = nil
}
