// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core/endpoint/variable.proto

package endpoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariableType int32

const (
	VariableType_VARIABLE_TYPE_UNSPECIFIED VariableType = 0
	VariableType_VARIABLE_TYPE_STRING      VariableType = 1
	VariableType_VARIABLE_TYPE_INT         VariableType = 2
	VariableType_VARIABLE_TYPE_FLOAT       VariableType = 3
	VariableType_VARIABLE_TYPE_BOOL        VariableType = 4
	VariableType_VARIABLE_TYPE_OBJECT      VariableType = 5
)

// Enum value maps for VariableType.
var (
	VariableType_name = map[int32]string{
		0: "VARIABLE_TYPE_UNSPECIFIED",
		1: "VARIABLE_TYPE_STRING",
		2: "VARIABLE_TYPE_INT",
		3: "VARIABLE_TYPE_FLOAT",
		4: "VARIABLE_TYPE_BOOL",
		5: "VARIABLE_TYPE_OBJECT",
	}
	VariableType_value = map[string]int32{
		"VARIABLE_TYPE_UNSPECIFIED": 0,
		"VARIABLE_TYPE_STRING":      1,
		"VARIABLE_TYPE_INT":         2,
		"VARIABLE_TYPE_FLOAT":       3,
		"VARIABLE_TYPE_BOOL":        4,
		"VARIABLE_TYPE_OBJECT":      5,
	}
)

func (x VariableType) Enum() *VariableType {
	p := new(VariableType)
	*p = x
	return p
}

func (x VariableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariableType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_endpoint_variable_proto_enumTypes[0].Descriptor()
}

func (VariableType) Type() protoreflect.EnumType {
	return &file_core_endpoint_variable_proto_enumTypes[0]
}

func (x VariableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariableType.Descriptor instead.
func (VariableType) EnumDescriptor() ([]byte, []int) {
	return file_core_endpoint_variable_proto_rawDescGZIP(), []int{0}
}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          VariableType           `protobuf:"varint,1,opt,name=type,proto3,enum=endpoint.VariableType" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_core_endpoint_variable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_variable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_core_endpoint_variable_proto_rawDescGZIP(), []int{0}
}

func (x *Variable) GetType() VariableType {
	if x != nil {
		return x.Type
	}
	return VariableType_VARIABLE_TYPE_UNSPECIFIED
}

func (x *Variable) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Variable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Variable) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

var File_core_endpoint_variable_proto protoreflect.FileDescriptor

const file_core_endpoint_variable_proto_rawDesc = "" +
	"\n" +
	"\x1ccore/endpoint/variable.proto\x12\bendpoint\"\x82\x01\n" +
	"\bVariable\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.endpoint.VariableTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault*\xa9\x01\n" +
	"\fVariableType\x12\x1d\n" +
	"\x19VARIABLE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14VARIABLE_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11VARIABLE_TYPE_INT\x10\x02\x12\x17\n" +
	"\x13VARIABLE_TYPE_FLOAT\x10\x03\x12\x16\n" +
	"\x12VARIABLE_TYPE_BOOL\x10\x04\x12\x18\n" +
	"\x14VARIABLE_TYPE_OBJECT\x10\x05B\x8d\x01\n" +
	"\fcom.endpointB\rVariableProtoP\x01Z.github.com/ideagate/model/gen-go/core/endpoint\xa2\x02\x03EXX\xaa\x02\bEndpoint\xca\x02\bEndpoint\xe2\x02\x14Endpoint\\GPBMetadata\xea\x02\bEndpointb\x06proto3"

var (
	file_core_endpoint_variable_proto_rawDescOnce sync.Once
	file_core_endpoint_variable_proto_rawDescData []byte
)

func file_core_endpoint_variable_proto_rawDescGZIP() []byte {
	file_core_endpoint_variable_proto_rawDescOnce.Do(func() {
		file_core_endpoint_variable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_endpoint_variable_proto_rawDesc), len(file_core_endpoint_variable_proto_rawDesc)))
	})
	return file_core_endpoint_variable_proto_rawDescData
}

var file_core_endpoint_variable_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_endpoint_variable_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_endpoint_variable_proto_goTypes = []any{
	(VariableType)(0), // 0: endpoint.VariableType
	(*Variable)(nil),  // 1: endpoint.Variable
}
var file_core_endpoint_variable_proto_depIdxs = []int32{
	0, // 0: endpoint.Variable.type:type_name -> endpoint.VariableType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_endpoint_variable_proto_init() }
func file_core_endpoint_variable_proto_init() {
	if File_core_endpoint_variable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_endpoint_variable_proto_rawDesc), len(file_core_endpoint_variable_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_endpoint_variable_proto_goTypes,
		DependencyIndexes: file_core_endpoint_variable_proto_depIdxs,
		EnumInfos:         file_core_endpoint_variable_proto_enumTypes,
		MessageInfos:      file_core_endpoint_variable_proto_msgTypes,
	}.Build()
	File_core_endpoint_variable_proto = out.File
	file_core_endpoint_variable_proto_goTypes = nil
	file_core_endpoint_variable_proto_depIdxs = nil
}
