// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/endpoint/workflow.proto

package endpoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StepType int32

const (
	StepType_STEP_TYPE_UNSPECIFIED StepType = 0
	StepType_STEP_TYPE_START       StepType = 1
	StepType_STEP_TYPE_END         StepType = 2
	StepType_STEP_TYPE_SLEEP       StepType = 3
	StepType_STEP_TYPE_SCRIPT_JS   StepType = 4
	StepType_STEP_TYPE_CONDITION   StepType = 5
	StepType_STEP_TYPE_REST        StepType = 6
	StepType_STEP_TYPE_MYSQL       StepType = 7
	StepType_STEP_TYPE_POSTGRESQL  StepType = 8
	StepType_STEP_TYPE_REDIS       StepType = 9
)

// Enum value maps for StepType.
var (
	StepType_name = map[int32]string{
		0: "STEP_TYPE_UNSPECIFIED",
		1: "STEP_TYPE_START",
		2: "STEP_TYPE_END",
		3: "STEP_TYPE_SLEEP",
		4: "STEP_TYPE_SCRIPT_JS",
		5: "STEP_TYPE_CONDITION",
		6: "STEP_TYPE_REST",
		7: "STEP_TYPE_MYSQL",
		8: "STEP_TYPE_POSTGRESQL",
		9: "STEP_TYPE_REDIS",
	}
	StepType_value = map[string]int32{
		"STEP_TYPE_UNSPECIFIED": 0,
		"STEP_TYPE_START":       1,
		"STEP_TYPE_END":         2,
		"STEP_TYPE_SLEEP":       3,
		"STEP_TYPE_SCRIPT_JS":   4,
		"STEP_TYPE_CONDITION":   5,
		"STEP_TYPE_REST":        6,
		"STEP_TYPE_MYSQL":       7,
		"STEP_TYPE_POSTGRESQL":  8,
		"STEP_TYPE_REDIS":       9,
	}
)

func (x StepType) Enum() *StepType {
	p := new(StepType)
	*p = x
	return p
}

func (x StepType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_endpoint_workflow_proto_enumTypes[0].Descriptor()
}

func (StepType) Type() protoreflect.EnumType {
	return &file_core_endpoint_workflow_proto_enumTypes[0]
}

func (x StepType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepType.Descriptor instead.
func (StepType) EnumDescriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{0}
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EntrypointId  string                 `protobuf:"bytes,2,opt,name=entrypoint_id,json=entrypointId,proto3" json:"entrypoint_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Steps         []*Step                `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,8,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *Workflow) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Workflow) GetEntrypointId() string {
	if x != nil {
		return x.EntrypointId
	}
	return ""
}

func (x *Workflow) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Workflow) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Workflow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workflow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Workflow) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Workflow) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Step struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type      StepType               `protobuf:"varint,3,opt,name=type,proto3,enum=endpoint.StepType" json:"type,omitempty"`
	Variables map[string]*Variable   `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs   map[string]*Variable   `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Returns   []*Return              `protobuf:"bytes,6,rep,name=returns,proto3" json:"returns,omitempty"`
	Graph     *Graph                 `protobuf:"bytes,7,opt,name=graph,proto3" json:"graph,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*Step_ActionEnd
	//	*Step_ActionMysql
	//	*Step_ActionRest
	//	*Step_ActionSleep
	Action        isStep_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetType() StepType {
	if x != nil {
		return x.Type
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (x *Step) GetVariables() map[string]*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Step) GetOutputs() map[string]*Variable {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Step) GetReturns() []*Return {
	if x != nil {
		return x.Returns
	}
	return nil
}

func (x *Step) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *Step) GetAction() isStep_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Step) GetActionEnd() *ActionEnd {
	if x != nil {
		if x, ok := x.Action.(*Step_ActionEnd); ok {
			return x.ActionEnd
		}
	}
	return nil
}

func (x *Step) GetActionMysql() *ActionMysql {
	if x != nil {
		if x, ok := x.Action.(*Step_ActionMysql); ok {
			return x.ActionMysql
		}
	}
	return nil
}

func (x *Step) GetActionRest() *ActionRest {
	if x != nil {
		if x, ok := x.Action.(*Step_ActionRest); ok {
			return x.ActionRest
		}
	}
	return nil
}

func (x *Step) GetActionSleep() *ActionSleep {
	if x != nil {
		if x, ok := x.Action.(*Step_ActionSleep); ok {
			return x.ActionSleep
		}
	}
	return nil
}

type isStep_Action interface {
	isStep_Action()
}

type Step_ActionEnd struct {
	ActionEnd *ActionEnd `protobuf:"bytes,101,opt,name=action_end,json=actionEnd,proto3,oneof"`
}

type Step_ActionMysql struct {
	ActionMysql *ActionMysql `protobuf:"bytes,102,opt,name=action_mysql,json=actionMysql,proto3,oneof"`
}

type Step_ActionRest struct {
	ActionRest *ActionRest `protobuf:"bytes,103,opt,name=action_rest,json=actionRest,proto3,oneof"`
}

type Step_ActionSleep struct {
	ActionSleep *ActionSleep `protobuf:"bytes,104,opt,name=action_sleep,json=actionSleep,proto3,oneof"`
}

func (*Step_ActionEnd) isStep_Action() {}

func (*Step_ActionMysql) isStep_Action() {}

func (*Step_ActionRest) isStep_Action() {}

func (*Step_ActionSleep) isStep_Action() {}

type ActionEnd struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReturnDataFromStepIds []string               `protobuf:"bytes,1,rep,name=return_data_from_step_ids,json=returnDataFromStepIds,proto3" json:"return_data_from_step_ids,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ActionEnd) Reset() {
	*x = ActionEnd{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEnd) ProtoMessage() {}

func (x *ActionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEnd.ProtoReflect.Descriptor instead.
func (*ActionEnd) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *ActionEnd) GetReturnDataFromStepIds() []string {
	if x != nil {
		return x.ReturnDataFromStepIds
	}
	return nil
}

type ActionMysql struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataSourceId  string                 `protobuf:"bytes,1,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	Queries       []*Query               `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionMysql) Reset() {
	*x = ActionMysql{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionMysql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionMysql) ProtoMessage() {}

func (x *ActionMysql) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionMysql.ProtoReflect.Descriptor instead.
func (*ActionMysql) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *ActionMysql) GetDataSourceId() string {
	if x != nil {
		return x.DataSourceId
	}
	return ""
}

func (x *ActionMysql) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

type ActionRest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *Variable              `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]*Variable   `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestType   string                 `protobuf:"bytes,4,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	RequestBody   string                 `protobuf:"bytes,5,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRest) Reset() {
	*x = ActionRest{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRest) ProtoMessage() {}

func (x *ActionRest) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRest.ProtoReflect.Descriptor instead.
func (*ActionRest) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ActionRest) GetPath() *Variable {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *ActionRest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ActionRest) GetHeaders() map[string]*Variable {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ActionRest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *ActionRest) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

type ActionSleep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs     int64                  `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSleep) Reset() {
	*x = ActionSleep{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSleep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSleep) ProtoMessage() {}

func (x *ActionSleep) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSleep.ProtoReflect.Descriptor instead.
func (*ActionSleep) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ActionSleep) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Variable              `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Parameters    []*Variable            `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *Query) GetQuery() *Variable {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Query) GetParameters() []*Variable {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Return struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsFinishCondition string                 `protobuf:"bytes,3,opt,name=is_finish_condition,json=isFinishCondition,proto3" json:"is_finish_condition,omitempty"`
	NextStepId        string                 `protobuf:"bytes,4,opt,name=next_step_id,json=nextStepId,proto3" json:"next_step_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Return) Reset() {
	*x = Return{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return) ProtoMessage() {}

func (x *Return) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return.ProtoReflect.Descriptor instead.
func (*Return) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *Return) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Return) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Return) GetIsFinishCondition() string {
	if x != nil {
		return x.IsFinishCondition
	}
	return ""
}

func (x *Return) GetNextStepId() string {
	if x != nil {
		return x.NextStepId
	}
	return ""
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConditionId   string                 `protobuf:"bytes,2,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Dest          string                 `protobuf:"bytes,4,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetConditionId() string {
	if x != nil {
		return x.ConditionId
	}
	return ""
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionX     int32                  `protobuf:"varint,1,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY     int32                  `protobuf:"varint,2,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_core_endpoint_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_core_endpoint_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_core_endpoint_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *Graph) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *Graph) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

var File_core_endpoint_workflow_proto protoreflect.FileDescriptor

const file_core_endpoint_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1ccore/endpoint/workflow.proto\x12\bendpoint\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ccore/endpoint/variable.proto\"\xd1\x02\n" +
	"\bWorkflow\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12#\n" +
	"\rentrypoint_id\x18\x02 \x01(\tR\fentrypointId\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\x05steps\x18\a \x03(\v2\x0e.endpoint.StepR\x05steps\x12$\n" +
	"\x05edges\x18\b \x03(\v2\x0e.endpoint.EdgeR\x05edges\"\xac\x05\n" +
	"\x04Step\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.endpoint.StepTypeR\x04type\x12;\n" +
	"\tvariables\x18\x04 \x03(\v2\x1d.endpoint.Step.VariablesEntryR\tvariables\x125\n" +
	"\aoutputs\x18\x05 \x03(\v2\x1b.endpoint.Step.OutputsEntryR\aoutputs\x12*\n" +
	"\areturns\x18\x06 \x03(\v2\x10.endpoint.ReturnR\areturns\x12%\n" +
	"\x05graph\x18\a \x01(\v2\x0f.endpoint.GraphR\x05graph\x124\n" +
	"\n" +
	"action_end\x18e \x01(\v2\x13.endpoint.ActionEndH\x00R\tactionEnd\x12:\n" +
	"\faction_mysql\x18f \x01(\v2\x15.endpoint.ActionMysqlH\x00R\vactionMysql\x127\n" +
	"\vaction_rest\x18g \x01(\v2\x14.endpoint.ActionRestH\x00R\n" +
	"actionRest\x12:\n" +
	"\faction_sleep\x18h \x01(\v2\x15.endpoint.ActionSleepH\x00R\vactionSleep\x1aP\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\x1aN\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01B\b\n" +
	"\x06action\"E\n" +
	"\tActionEnd\x128\n" +
	"\x19return_data_from_step_ids\x18\x01 \x03(\tR\x15returnDataFromStepIds\"^\n" +
	"\vActionMysql\x12$\n" +
	"\x0edata_source_id\x18\x01 \x01(\tR\fdataSourceId\x12)\n" +
	"\aqueries\x18\x02 \x03(\v2\x0f.endpoint.QueryR\aqueries\"\x9f\x02\n" +
	"\n" +
	"ActionRest\x12&\n" +
	"\x04path\x18\x01 \x01(\v2\x12.endpoint.VariableR\x04path\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12;\n" +
	"\aheaders\x18\x03 \x03(\v2!.endpoint.ActionRest.HeadersEntryR\aheaders\x12!\n" +
	"\frequest_type\x18\x04 \x01(\tR\vrequestType\x12!\n" +
	"\frequest_body\x18\x05 \x01(\tR\vrequestBody\x1aN\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.endpoint.VariableR\x05value:\x028\x01\",\n" +
	"\vActionSleep\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x03R\ttimeoutMs\"e\n" +
	"\x05Query\x12(\n" +
	"\x05query\x18\x01 \x01(\v2\x12.endpoint.VariableR\x05query\x122\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x12.endpoint.VariableR\n" +
	"parameters\"~\n" +
	"\x06Return\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13is_finish_condition\x18\x03 \x01(\tR\x11isFinishCondition\x12 \n" +
	"\fnext_step_id\x18\x04 \x01(\tR\n" +
	"nextStepId\"e\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcondition_id\x18\x02 \x01(\tR\vconditionId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04dest\x18\x04 \x01(\tR\x04dest\"E\n" +
	"\x05Graph\x12\x1d\n" +
	"\n" +
	"position_x\x18\x01 \x01(\x05R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\x02 \x01(\x05R\tpositionY*\xec\x01\n" +
	"\bStepType\x12\x19\n" +
	"\x15STEP_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTEP_TYPE_START\x10\x01\x12\x11\n" +
	"\rSTEP_TYPE_END\x10\x02\x12\x13\n" +
	"\x0fSTEP_TYPE_SLEEP\x10\x03\x12\x17\n" +
	"\x13STEP_TYPE_SCRIPT_JS\x10\x04\x12\x17\n" +
	"\x13STEP_TYPE_CONDITION\x10\x05\x12\x12\n" +
	"\x0eSTEP_TYPE_REST\x10\x06\x12\x13\n" +
	"\x0fSTEP_TYPE_MYSQL\x10\a\x12\x18\n" +
	"\x14STEP_TYPE_POSTGRESQL\x10\b\x12\x13\n" +
	"\x0fSTEP_TYPE_REDIS\x10\tB\x8d\x01\n" +
	"\fcom.endpointB\rWorkflowProtoP\x01Z.github.com/ideagate/model/gen-go/core/endpoint\xa2\x02\x03EXX\xaa\x02\bEndpoint\xca\x02\bEndpoint\xe2\x02\x14Endpoint\\GPBMetadata\xea\x02\bEndpointb\x06proto3"

var (
	file_core_endpoint_workflow_proto_rawDescOnce sync.Once
	file_core_endpoint_workflow_proto_rawDescData []byte
)

func file_core_endpoint_workflow_proto_rawDescGZIP() []byte {
	file_core_endpoint_workflow_proto_rawDescOnce.Do(func() {
		file_core_endpoint_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_endpoint_workflow_proto_rawDesc), len(file_core_endpoint_workflow_proto_rawDesc)))
	})
	return file_core_endpoint_workflow_proto_rawDescData
}

var file_core_endpoint_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_endpoint_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_core_endpoint_workflow_proto_goTypes = []any{
	(StepType)(0),                 // 0: endpoint.StepType
	(*Workflow)(nil),              // 1: endpoint.Workflow
	(*Step)(nil),                  // 2: endpoint.Step
	(*ActionEnd)(nil),             // 3: endpoint.ActionEnd
	(*ActionMysql)(nil),           // 4: endpoint.ActionMysql
	(*ActionRest)(nil),            // 5: endpoint.ActionRest
	(*ActionSleep)(nil),           // 6: endpoint.ActionSleep
	(*Query)(nil),                 // 7: endpoint.Query
	(*Return)(nil),                // 8: endpoint.Return
	(*Edge)(nil),                  // 9: endpoint.Edge
	(*Graph)(nil),                 // 10: endpoint.Graph
	nil,                           // 11: endpoint.Step.VariablesEntry
	nil,                           // 12: endpoint.Step.OutputsEntry
	nil,                           // 13: endpoint.ActionRest.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*Variable)(nil),              // 15: endpoint.Variable
}
var file_core_endpoint_workflow_proto_depIdxs = []int32{
	14, // 0: endpoint.Workflow.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: endpoint.Workflow.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: endpoint.Workflow.steps:type_name -> endpoint.Step
	9,  // 3: endpoint.Workflow.edges:type_name -> endpoint.Edge
	0,  // 4: endpoint.Step.type:type_name -> endpoint.StepType
	11, // 5: endpoint.Step.variables:type_name -> endpoint.Step.VariablesEntry
	12, // 6: endpoint.Step.outputs:type_name -> endpoint.Step.OutputsEntry
	8,  // 7: endpoint.Step.returns:type_name -> endpoint.Return
	10, // 8: endpoint.Step.graph:type_name -> endpoint.Graph
	3,  // 9: endpoint.Step.action_end:type_name -> endpoint.ActionEnd
	4,  // 10: endpoint.Step.action_mysql:type_name -> endpoint.ActionMysql
	5,  // 11: endpoint.Step.action_rest:type_name -> endpoint.ActionRest
	6,  // 12: endpoint.Step.action_sleep:type_name -> endpoint.ActionSleep
	7,  // 13: endpoint.ActionMysql.queries:type_name -> endpoint.Query
	15, // 14: endpoint.ActionRest.path:type_name -> endpoint.Variable
	13, // 15: endpoint.ActionRest.headers:type_name -> endpoint.ActionRest.HeadersEntry
	15, // 16: endpoint.Query.query:type_name -> endpoint.Variable
	15, // 17: endpoint.Query.parameters:type_name -> endpoint.Variable
	15, // 18: endpoint.Step.VariablesEntry.value:type_name -> endpoint.Variable
	15, // 19: endpoint.Step.OutputsEntry.value:type_name -> endpoint.Variable
	15, // 20: endpoint.ActionRest.HeadersEntry.value:type_name -> endpoint.Variable
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_core_endpoint_workflow_proto_init() }
func file_core_endpoint_workflow_proto_init() {
	if File_core_endpoint_workflow_proto != nil {
		return
	}
	file_core_endpoint_variable_proto_init()
	file_core_endpoint_workflow_proto_msgTypes[1].OneofWrappers = []any{
		(*Step_ActionEnd)(nil),
		(*Step_ActionMysql)(nil),
		(*Step_ActionRest)(nil),
		(*Step_ActionSleep)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_endpoint_workflow_proto_rawDesc), len(file_core_endpoint_workflow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_endpoint_workflow_proto_goTypes,
		DependencyIndexes: file_core_endpoint_workflow_proto_depIdxs,
		EnumInfos:         file_core_endpoint_workflow_proto_enumTypes,
		MessageInfos:      file_core_endpoint_workflow_proto_msgTypes,
	}.Build()
	File_core_endpoint_workflow_proto = out.File
	file_core_endpoint_workflow_proto_goTypes = nil
	file_core_endpoint_workflow_proto_depIdxs = nil
}
