// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/entrypoint/process/mysql.proto" (package "process", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Query } from "./query";
/**
 * @generated from protobuf message process.Mysql
 */
export interface Mysql {
    /**
     * @generated from protobuf field: string dependency_id = 1;
     */
    dependencyId: string;
    /**
     * @generated from protobuf field: repeated process.Query queries = 2;
     */
    queries: Query[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Mysql$Type extends MessageType<Mysql> {
    constructor() {
        super("process.Mysql", [
            { no: 1, name: "dependency_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "queries", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Query }
        ]);
    }
    create(value?: PartialMessage<Mysql>): Mysql {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.dependencyId = "";
        message.queries = [];
        if (value !== undefined)
            reflectionMergePartial<Mysql>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Mysql): Mysql {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string dependency_id */ 1:
                    message.dependencyId = reader.string();
                    break;
                case /* repeated process.Query queries */ 2:
                    message.queries.push(Query.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Mysql, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string dependency_id = 1; */
        if (message.dependencyId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.dependencyId);
        /* repeated process.Query queries = 2; */
        for (let i = 0; i < message.queries.length; i++)
            Query.internalBinaryWrite(message.queries[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message process.Mysql
 */
export const Mysql = new Mysql$Type();
