// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/entrypoint/process/nats.proto" (package "process", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Variable } from "../variable/variable";
/**
 * @generated from protobuf message process.NatsPublisher
 */
export interface NatsPublisher {
    /**
     * @generated from protobuf field: string dependency_id = 1;
     */
    dependencyId: string;
    /**
     * @generated from protobuf field: variable.Variable subject = 2;
     */
    subject?: Variable;
    /**
     * @generated from protobuf field: variable.Variable message = 3;
     */
    message?: Variable;
}
// @generated message type with reflection information, may provide speed optimized methods
class NatsPublisher$Type extends MessageType<NatsPublisher> {
    constructor() {
        super("process.NatsPublisher", [
            { no: 1, name: "dependency_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "subject", kind: "message", T: () => Variable },
            { no: 3, name: "message", kind: "message", T: () => Variable }
        ]);
    }
    create(value?: PartialMessage<NatsPublisher>): NatsPublisher {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.dependencyId = "";
        if (value !== undefined)
            reflectionMergePartial<NatsPublisher>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NatsPublisher): NatsPublisher {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string dependency_id */ 1:
                    message.dependencyId = reader.string();
                    break;
                case /* variable.Variable subject */ 2:
                    message.subject = Variable.internalBinaryRead(reader, reader.uint32(), options, message.subject);
                    break;
                case /* variable.Variable message */ 3:
                    message.message = Variable.internalBinaryRead(reader, reader.uint32(), options, message.message);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NatsPublisher, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string dependency_id = 1; */
        if (message.dependencyId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.dependencyId);
        /* variable.Variable subject = 2; */
        if (message.subject)
            Variable.internalBinaryWrite(message.subject, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* variable.Variable message = 3; */
        if (message.message)
            Variable.internalBinaryWrite(message.message, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message process.NatsPublisher
 */
export const NatsPublisher = new NatsPublisher$Type();
