// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/entrypoint/process/query.proto" (package "process", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Variable } from "../variable/variable";
/**
 * @generated from protobuf message process.Query
 */
export interface Query {
    /**
     * @generated from protobuf field: variable.Variable query = 1;
     */
    query?: Variable;
    /**
     * @generated from protobuf field: map<string, variable.Variable> params = 2;
     */
    params: {
        [key: string]: Variable;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class Query$Type extends MessageType<Query> {
    constructor() {
        super("process.Query", [
            { no: 1, name: "query", kind: "message", T: () => Variable },
            { no: 2, name: "params", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => Variable } }
        ]);
    }
    create(value?: PartialMessage<Query>): Query {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.params = {};
        if (value !== undefined)
            reflectionMergePartial<Query>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Query): Query {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* variable.Variable query */ 1:
                    message.query = Variable.internalBinaryRead(reader, reader.uint32(), options, message.query);
                    break;
                case /* map<string, variable.Variable> params */ 2:
                    this.binaryReadMap2(message.params, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: Query["params"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof Query["params"] | undefined, val: Query["params"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = Variable.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for field process.Query.params");
            }
        }
        map[key ?? ""] = val ?? Variable.create();
    }
    internalBinaryWrite(message: Query, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* variable.Variable query = 1; */
        if (message.query)
            Variable.internalBinaryWrite(message.query, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* map<string, variable.Variable> params = 2; */
        for (let k of globalThis.Object.keys(message.params)) {
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            Variable.internalBinaryWrite(message.params[k], writer, options);
            writer.join().join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message process.Query
 */
export const Query = new Query$Type();
