// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/entrypoint/process/switch.proto" (package "process", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Variable } from "../variable/variable";
/**
 * @generated from protobuf message process.Switch
 */
export interface Switch {
    /**
     * @generated from protobuf field: variable.Variable input = 1;
     */
    input?: Variable;
    /**
     * @generated from protobuf field: repeated process.SwitchCase cases = 2;
     */
    cases: SwitchCase[];
}
/**
 * @generated from protobuf message process.SwitchCase
 */
export interface SwitchCase {
    /**
     * @generated from protobuf field: variable.Variable equal = 1;
     */
    equal?: Variable;
    /**
     * @generated from protobuf field: string output_id = 2;
     */
    outputId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Switch$Type extends MessageType<Switch> {
    constructor() {
        super("process.Switch", [
            { no: 1, name: "input", kind: "message", T: () => Variable },
            { no: 2, name: "cases", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SwitchCase }
        ]);
    }
    create(value?: PartialMessage<Switch>): Switch {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cases = [];
        if (value !== undefined)
            reflectionMergePartial<Switch>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Switch): Switch {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* variable.Variable input */ 1:
                    message.input = Variable.internalBinaryRead(reader, reader.uint32(), options, message.input);
                    break;
                case /* repeated process.SwitchCase cases */ 2:
                    message.cases.push(SwitchCase.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Switch, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* variable.Variable input = 1; */
        if (message.input)
            Variable.internalBinaryWrite(message.input, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated process.SwitchCase cases = 2; */
        for (let i = 0; i < message.cases.length; i++)
            SwitchCase.internalBinaryWrite(message.cases[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message process.Switch
 */
export const Switch = new Switch$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SwitchCase$Type extends MessageType<SwitchCase> {
    constructor() {
        super("process.SwitchCase", [
            { no: 1, name: "equal", kind: "message", T: () => Variable },
            { no: 2, name: "output_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SwitchCase>): SwitchCase {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.outputId = "";
        if (value !== undefined)
            reflectionMergePartial<SwitchCase>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SwitchCase): SwitchCase {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* variable.Variable equal */ 1:
                    message.equal = Variable.internalBinaryRead(reader, reader.uint32(), options, message.equal);
                    break;
                case /* string output_id */ 2:
                    message.outputId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SwitchCase, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* variable.Variable equal = 1; */
        if (message.equal)
            Variable.internalBinaryWrite(message.equal, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string output_id = 2; */
        if (message.outputId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.outputId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message process.SwitchCase
 */
export const SwitchCase = new SwitchCase$Type();
