// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dashboard/service.proto

package dashboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_dashboard_service_proto protoreflect.FileDescriptor

const file_dashboard_service_proto_rawDesc = "" +
	"\n" +
	"\x17dashboard/service.proto\x12\tdashboard\x1a\x17dashboard/project.proto\x1a\x1bdashboard/application.proto\x1a\x18dashboard/endpoint.proto2\xc2\x06\n" +
	"\x10DashboardService\x12U\n" +
	"\x0eGetListProject\x12 .dashboard.GetListProjectRequest\x1a!.dashboard.GetListProjectResponse\x12R\n" +
	"\rCreateProject\x12\x1f.dashboard.CreateProjectRequest\x1a .dashboard.CreateProjectResponse\x12R\n" +
	"\rUpdateProject\x12\x1f.dashboard.UpdateProjectRequest\x1a .dashboard.UpdateProjectResponse\x12R\n" +
	"\rDeleteProject\x12\x1f.dashboard.DeleteProjectRequest\x1a .dashboard.DeleteProjectResponse\x12a\n" +
	"\x12GetListApplication\x12$.dashboard.GetListApplicationRequest\x1a%.dashboard.GetListApplicationResponse\x12^\n" +
	"\x11CreateApplication\x12#.dashboard.CreateApplicationRequest\x1a$.dashboard.CreateApplicationResponse\x12^\n" +
	"\x11UpdateApplication\x12#.dashboard.UpdateApplicationRequest\x1a$.dashboard.UpdateApplicationResponse\x12^\n" +
	"\x11DeleteApplication\x12#.dashboard.DeleteApplicationRequest\x1a$.dashboard.DeleteApplicationResponse\x12X\n" +
	"\x0fGetListEndpoint\x12!.dashboard.GetListEndpointRequest\x1a\".dashboard.GetListEndpointResponseB\x8d\x01\n" +
	"\rcom.dashboardB\fServiceProtoP\x01Z*github.com/ideagate/model/gen-go/dashboard\xa2\x02\x03DXX\xaa\x02\tDashboard\xca\x02\tDashboard\xe2\x02\x15Dashboard\\GPBMetadata\xea\x02\tDashboardb\x06proto3"

var file_dashboard_service_proto_goTypes = []any{
	(*GetListProjectRequest)(nil),      // 0: dashboard.GetListProjectRequest
	(*CreateProjectRequest)(nil),       // 1: dashboard.CreateProjectRequest
	(*UpdateProjectRequest)(nil),       // 2: dashboard.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),       // 3: dashboard.DeleteProjectRequest
	(*GetListApplicationRequest)(nil),  // 4: dashboard.GetListApplicationRequest
	(*CreateApplicationRequest)(nil),   // 5: dashboard.CreateApplicationRequest
	(*UpdateApplicationRequest)(nil),   // 6: dashboard.UpdateApplicationRequest
	(*DeleteApplicationRequest)(nil),   // 7: dashboard.DeleteApplicationRequest
	(*GetListEndpointRequest)(nil),     // 8: dashboard.GetListEndpointRequest
	(*GetListProjectResponse)(nil),     // 9: dashboard.GetListProjectResponse
	(*CreateProjectResponse)(nil),      // 10: dashboard.CreateProjectResponse
	(*UpdateProjectResponse)(nil),      // 11: dashboard.UpdateProjectResponse
	(*DeleteProjectResponse)(nil),      // 12: dashboard.DeleteProjectResponse
	(*GetListApplicationResponse)(nil), // 13: dashboard.GetListApplicationResponse
	(*CreateApplicationResponse)(nil),  // 14: dashboard.CreateApplicationResponse
	(*UpdateApplicationResponse)(nil),  // 15: dashboard.UpdateApplicationResponse
	(*DeleteApplicationResponse)(nil),  // 16: dashboard.DeleteApplicationResponse
	(*GetListEndpointResponse)(nil),    // 17: dashboard.GetListEndpointResponse
}
var file_dashboard_service_proto_depIdxs = []int32{
	0,  // 0: dashboard.DashboardService.GetListProject:input_type -> dashboard.GetListProjectRequest
	1,  // 1: dashboard.DashboardService.CreateProject:input_type -> dashboard.CreateProjectRequest
	2,  // 2: dashboard.DashboardService.UpdateProject:input_type -> dashboard.UpdateProjectRequest
	3,  // 3: dashboard.DashboardService.DeleteProject:input_type -> dashboard.DeleteProjectRequest
	4,  // 4: dashboard.DashboardService.GetListApplication:input_type -> dashboard.GetListApplicationRequest
	5,  // 5: dashboard.DashboardService.CreateApplication:input_type -> dashboard.CreateApplicationRequest
	6,  // 6: dashboard.DashboardService.UpdateApplication:input_type -> dashboard.UpdateApplicationRequest
	7,  // 7: dashboard.DashboardService.DeleteApplication:input_type -> dashboard.DeleteApplicationRequest
	8,  // 8: dashboard.DashboardService.GetListEndpoint:input_type -> dashboard.GetListEndpointRequest
	9,  // 9: dashboard.DashboardService.GetListProject:output_type -> dashboard.GetListProjectResponse
	10, // 10: dashboard.DashboardService.CreateProject:output_type -> dashboard.CreateProjectResponse
	11, // 11: dashboard.DashboardService.UpdateProject:output_type -> dashboard.UpdateProjectResponse
	12, // 12: dashboard.DashboardService.DeleteProject:output_type -> dashboard.DeleteProjectResponse
	13, // 13: dashboard.DashboardService.GetListApplication:output_type -> dashboard.GetListApplicationResponse
	14, // 14: dashboard.DashboardService.CreateApplication:output_type -> dashboard.CreateApplicationResponse
	15, // 15: dashboard.DashboardService.UpdateApplication:output_type -> dashboard.UpdateApplicationResponse
	16, // 16: dashboard.DashboardService.DeleteApplication:output_type -> dashboard.DeleteApplicationResponse
	17, // 17: dashboard.DashboardService.GetListEndpoint:output_type -> dashboard.GetListEndpointResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_dashboard_service_proto_init() }
func file_dashboard_service_proto_init() {
	if File_dashboard_service_proto != nil {
		return
	}
	file_dashboard_project_proto_init()
	file_dashboard_application_proto_init()
	file_dashboard_endpoint_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_service_proto_rawDesc), len(file_dashboard_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_service_proto_goTypes,
		DependencyIndexes: file_dashboard_service_proto_depIdxs,
	}.Build()
	File_dashboard_service_proto = out.File
	file_dashboard_service_proto_goTypes = nil
	file_dashboard_service_proto_depIdxs = nil
}
