// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/entrypoint/entrypoint.proto" (package "entrypoint", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { SettingNatsConsumer } from "./settings";
import { Timestamp } from "../../google/protobuf/timestamp";
/**
 * @generated from protobuf message entrypoint.Entrypoint
 */
export interface Entrypoint {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string application_id = 2;
     */
    applicationId: string;
    /**
     * @generated from protobuf field: string project_id = 3;
     */
    projectId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 4;
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 5;
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: entrypoint.EntrypointType type = 6;
     */
    type: EntrypointType;
    /**
     * @generated from protobuf field: string name = 7;
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 8;
     */
    description: string;
    /**
     * @generated from protobuf field: entrypoint.Setting setting = 9;
     */
    setting?: Setting;
}
/**
 * @generated from protobuf message entrypoint.Setting
 */
export interface Setting {
    /**
     * @generated from protobuf field: entrypoint.SettingNatsConsumer setting_nats_consumer = 1;
     */
    settingNatsConsumer?: SettingNatsConsumer;
}
/**
 * @generated from protobuf enum entrypoint.EntrypointType
 */
export enum EntrypointType {
    /**
     * @generated from protobuf enum value: ENTRYPOINT_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ENTRYPOINT_TYPE_REST = 1;
     */
    REST = 1,
    /**
     * @generated from protobuf enum value: ENTRYPOINT_TYPE_CRON = 2;
     */
    CRON = 2,
    /**
     * @generated from protobuf enum value: ENTRYPOINT_TYPE_NATS_CONSUMER = 3;
     */
    NATS_CONSUMER = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class Entrypoint$Type extends MessageType<Entrypoint> {
    constructor() {
        super("entrypoint.Entrypoint", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "application_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "project_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 6, name: "type", kind: "enum", T: () => ["entrypoint.EntrypointType", EntrypointType, "ENTRYPOINT_TYPE_"] },
            { no: 7, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "setting", kind: "message", T: () => Setting }
        ]);
    }
    create(value?: PartialMessage<Entrypoint>): Entrypoint {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.applicationId = "";
        message.projectId = "";
        message.type = 0;
        message.name = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<Entrypoint>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Entrypoint): Entrypoint {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string application_id */ 2:
                    message.applicationId = reader.string();
                    break;
                case /* string project_id */ 3:
                    message.projectId = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 4:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 5:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* entrypoint.EntrypointType type */ 6:
                    message.type = reader.int32();
                    break;
                case /* string name */ 7:
                    message.name = reader.string();
                    break;
                case /* string description */ 8:
                    message.description = reader.string();
                    break;
                case /* entrypoint.Setting setting */ 9:
                    message.setting = Setting.internalBinaryRead(reader, reader.uint32(), options, message.setting);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Entrypoint, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string application_id = 2; */
        if (message.applicationId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.applicationId);
        /* string project_id = 3; */
        if (message.projectId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.projectId);
        /* google.protobuf.Timestamp created_at = 4; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 5; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* entrypoint.EntrypointType type = 6; */
        if (message.type !== 0)
            writer.tag(6, WireType.Varint).int32(message.type);
        /* string name = 7; */
        if (message.name !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.name);
        /* string description = 8; */
        if (message.description !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.description);
        /* entrypoint.Setting setting = 9; */
        if (message.setting)
            Setting.internalBinaryWrite(message.setting, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entrypoint.Entrypoint
 */
export const Entrypoint = new Entrypoint$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Setting$Type extends MessageType<Setting> {
    constructor() {
        super("entrypoint.Setting", [
            { no: 1, name: "setting_nats_consumer", kind: "message", T: () => SettingNatsConsumer }
        ]);
    }
    create(value?: PartialMessage<Setting>): Setting {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Setting>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Setting): Setting {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* entrypoint.SettingNatsConsumer setting_nats_consumer */ 1:
                    message.settingNatsConsumer = SettingNatsConsumer.internalBinaryRead(reader, reader.uint32(), options, message.settingNatsConsumer);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Setting, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* entrypoint.SettingNatsConsumer setting_nats_consumer = 1; */
        if (message.settingNatsConsumer)
            SettingNatsConsumer.internalBinaryWrite(message.settingNatsConsumer, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entrypoint.Setting
 */
export const Setting = new Setting$Type();
