// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/entrypoint/settings.proto" (package "entrypoint", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message entrypoint.SettingNatsConsumer
 */
export interface SettingNatsConsumer {
    /**
     * @generated from protobuf field: string dependency_endpoint_id = 1;
     */
    dependencyEndpointId: string;
    /**
     * @generated from protobuf field: string consumer_name = 2;
     */
    consumerName: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class SettingNatsConsumer$Type extends MessageType<SettingNatsConsumer> {
    constructor() {
        super("entrypoint.SettingNatsConsumer", [
            { no: 1, name: "dependency_endpoint_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "consumer_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SettingNatsConsumer>): SettingNatsConsumer {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.dependencyEndpointId = "";
        message.consumerName = "";
        if (value !== undefined)
            reflectionMergePartial<SettingNatsConsumer>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SettingNatsConsumer): SettingNatsConsumer {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string dependency_endpoint_id */ 1:
                    message.dependencyEndpointId = reader.string();
                    break;
                case /* string consumer_name */ 2:
                    message.consumerName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SettingNatsConsumer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string dependency_endpoint_id = 1; */
        if (message.dependencyEndpointId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.dependencyEndpointId);
        /* string consumer_name = 2; */
        if (message.consumerName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.consumerName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entrypoint.SettingNatsConsumer
 */
export const SettingNatsConsumer = new SettingNatsConsumer$Type();
