// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/application/environment.proto

package application

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Id            string                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp             `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp             `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ProjectId     string                             `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ApplicationId string                             `protobuf:"bytes,5,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name          string                             `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Entrypoints   map[string]*EnvironmentEntrypoints `protobuf:"bytes,7,rep,name=entrypoints,proto3" json:"entrypoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_core_application_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_core_application_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_core_application_environment_proto_rawDescGZIP(), []int{0}
}

func (x *Environment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Environment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Environment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Environment) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Environment) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetEntrypoints() map[string]*EnvironmentEntrypoints {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

type EnvironmentEntrypoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rollout       *EnvironmentRollout    `protobuf:"bytes,1,opt,name=rollout,proto3" json:"rollout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentEntrypoints) Reset() {
	*x = EnvironmentEntrypoints{}
	mi := &file_core_application_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentEntrypoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentEntrypoints) ProtoMessage() {}

func (x *EnvironmentEntrypoints) ProtoReflect() protoreflect.Message {
	mi := &file_core_application_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentEntrypoints.ProtoReflect.Descriptor instead.
func (*EnvironmentEntrypoints) Descriptor() ([]byte, []int) {
	return file_core_application_environment_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentEntrypoints) GetRollout() *EnvironmentRollout {
	if x != nil {
		return x.Rollout
	}
	return nil
}

type EnvironmentRollout struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Canary        *EnvironmentRolloutItem `protobuf:"bytes,1,opt,name=canary,proto3" json:"canary,omitempty"`
	Stable        *EnvironmentRolloutItem `protobuf:"bytes,2,opt,name=stable,proto3" json:"stable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentRollout) Reset() {
	*x = EnvironmentRollout{}
	mi := &file_core_application_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentRollout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentRollout) ProtoMessage() {}

func (x *EnvironmentRollout) ProtoReflect() protoreflect.Message {
	mi := &file_core_application_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentRollout.ProtoReflect.Descriptor instead.
func (*EnvironmentRollout) Descriptor() ([]byte, []int) {
	return file_core_application_environment_proto_rawDescGZIP(), []int{2}
}

func (x *EnvironmentRollout) GetCanary() *EnvironmentRolloutItem {
	if x != nil {
		return x.Canary
	}
	return nil
}

func (x *EnvironmentRollout) GetStable() *EnvironmentRolloutItem {
	if x != nil {
		return x.Stable
	}
	return nil
}

type EnvironmentRolloutItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentRolloutItem) Reset() {
	*x = EnvironmentRolloutItem{}
	mi := &file_core_application_environment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentRolloutItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentRolloutItem) ProtoMessage() {}

func (x *EnvironmentRolloutItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_application_environment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentRolloutItem.ProtoReflect.Descriptor instead.
func (*EnvironmentRolloutItem) Descriptor() ([]byte, []int) {
	return file_core_application_environment_proto_rawDescGZIP(), []int{3}
}

func (x *EnvironmentRolloutItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EnvironmentRolloutItem) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_core_application_environment_proto protoreflect.FileDescriptor

const file_core_application_environment_proto_rawDesc = "" +
	"\n" +
	"\"core/application/environment.proto\x12\vapplication\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x03\n" +
	"\vEnvironment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12%\n" +
	"\x0eapplication_id\x18\x05 \x01(\tR\rapplicationId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12K\n" +
	"\ventrypoints\x18\a \x03(\v2).application.Environment.EntrypointsEntryR\ventrypoints\x1ac\n" +
	"\x10EntrypointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.application.EnvironmentEntrypointsR\x05value:\x028\x01\"S\n" +
	"\x16EnvironmentEntrypoints\x129\n" +
	"\arollout\x18\x01 \x01(\v2\x1f.application.EnvironmentRolloutR\arollout\"\x8e\x01\n" +
	"\x12EnvironmentRollout\x12;\n" +
	"\x06canary\x18\x01 \x01(\v2#.application.EnvironmentRolloutItemR\x06canary\x12;\n" +
	"\x06stable\x18\x02 \x01(\v2#.application.EnvironmentRolloutItemR\x06stable\"J\n" +
	"\x16EnvironmentRolloutItem\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weightB\xa2\x01\n" +
	"\x0fcom.applicationB\x10EnvironmentProtoP\x01Z1github.com/ideagate/model/gen-go/core/application\xa2\x02\x03AXX\xaa\x02\vApplication\xca\x02\vApplication\xe2\x02\x17Application\\GPBMetadata\xea\x02\vApplicationb\x06proto3"

var (
	file_core_application_environment_proto_rawDescOnce sync.Once
	file_core_application_environment_proto_rawDescData []byte
)

func file_core_application_environment_proto_rawDescGZIP() []byte {
	file_core_application_environment_proto_rawDescOnce.Do(func() {
		file_core_application_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_application_environment_proto_rawDesc), len(file_core_application_environment_proto_rawDesc)))
	})
	return file_core_application_environment_proto_rawDescData
}

var file_core_application_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_core_application_environment_proto_goTypes = []any{
	(*Environment)(nil),            // 0: application.Environment
	(*EnvironmentEntrypoints)(nil), // 1: application.EnvironmentEntrypoints
	(*EnvironmentRollout)(nil),     // 2: application.EnvironmentRollout
	(*EnvironmentRolloutItem)(nil), // 3: application.EnvironmentRolloutItem
	nil,                            // 4: application.Environment.EntrypointsEntry
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_core_application_environment_proto_depIdxs = []int32{
	5, // 0: application.Environment.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: application.Environment.updated_at:type_name -> google.protobuf.Timestamp
	4, // 2: application.Environment.entrypoints:type_name -> application.Environment.EntrypointsEntry
	2, // 3: application.EnvironmentEntrypoints.rollout:type_name -> application.EnvironmentRollout
	3, // 4: application.EnvironmentRollout.canary:type_name -> application.EnvironmentRolloutItem
	3, // 5: application.EnvironmentRollout.stable:type_name -> application.EnvironmentRolloutItem
	1, // 6: application.Environment.EntrypointsEntry.value:type_name -> application.EnvironmentEntrypoints
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_core_application_environment_proto_init() }
func file_core_application_environment_proto_init() {
	if File_core_application_environment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_application_environment_proto_rawDesc), len(file_core_application_environment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_application_environment_proto_goTypes,
		DependencyIndexes: file_core_application_environment_proto_depIdxs,
		MessageInfos:      file_core_application_environment_proto_msgTypes,
	}.Build()
	File_core_application_environment_proto = out.File
	file_core_application_environment_proto_goTypes = nil
	file_core_application_environment_proto_depIdxs = nil
}
