name: Publish Gen JS Package
on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0, v2.1, etc.

env:
  GEN_JS_FOLDER: gen-js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ${{ env.GEN_JS_FOLDER }}
        run: pnpm install --frozen-lockfile

      - name: Run build
        working-directory: ${{ env.GEN_JS_FOLDER }}
        run: pnpm build

      - name: Register GitHub Packages
        working-directory: ${{ env.GEN_JS_FOLDER }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            @ideagate:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$GH_TOKEN
          EOF

      - name: Publish to GitHub Packages
        working-directory: ${{ env.GEN_JS_FOLDER }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          pnpm version $VERSION
          pnpm publish --report-summary --access public --no-git-checks